### ISSUE TITLE
Validation?

### ISSUE THREAD

**Issue by epijim** [pharmaverse/pharmaverse#10]
from @rossfarrugia 

> Will have to consider later if we separate Validation into its own page where we can talk more around recommended strategy and which packages to use - shout if any thoughts on this?

**Comment by epijim** [comment]
As there are is existing working groups dedicated to qualification, validation and risk assessment - maybe we can focus on 'endorsing' one of the existing ones? 

From the Roche perspective - we are open sourcing our validation process very soon, and maybe if it's incorporated with valtools (to provide a way to both 'internally (Roche)' and 'externaly (Phuse)' validate R packages) - then both Phuse, Roche and R Consortium (plus I'm sure others internally) have methods to qualify R installations.

**Comment by rossfarrugia** [comment]
agree - would be happy to link to any other industry-level guidance that comes as long as it calls out a clear recommended strategy with the specific open source packages to use, as this is a common barrier to adopting R that we hear from programming heads. Myself and Michael R meet with Andy Nicholls and Doug tomorrow to share between GSK and Roche strategy

**Comment by epijim** [comment]
it's added (as we have some packages in that space)
