### ISSUE TITLE
Add sdtmchecks package placeholder to site

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#102]
Roche plans to release sdtmchecks later this year.

details needed from Will Harris:

- hex logo
- 1 liner explanation of what the package offers
- rough expected timing of open source release
- email of contact person

**Comment by harriscw** [comment]
Hi @rossfarrugia. 

Here's a one liner description: This package contains check functions to identify common SDTM issues that are generalizable, actionable, and meaningful for analysis.  I will follow up with a hex logo.  You can use either the email associated with this account or my roche email.  In terms of a timeline - our general plan was to create a repo for the package and slowly populate it throughout the year, hopefully having a decent version by fall or so.

**Comment by rossfarrugia** [comment]
Will add what we have for now @harriscw and send over a hex logo and we can add anytime.

**Comment by harriscw** [comment]
Hi @rossfarrugia, as of now we're thinking of calling the package `sdtmchecks2` just to differentiate from our existing internal package.  Here's a hex logo Edoardo whipped up.

![image](https://user-images.githubusercontent.com/36176570/156031003-2c6fdac1-fc12-436c-89b2-288a7c245aab.png)
