### ISSUE TITLE
Add WGs to contribute page

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#107]
Where to find WGs and members, scope/expectations (empowering them), not repeating effort of other industry groups, how to join/backfilling leavers etc

**Comment by rossfarrugia** [comment]
@MichaelRimler @mstackhouse @skalappu what do you think of the below text for WG members? following our discussions earlier in the week. If I get an OK from 1 or 2 of you i'll go ahead and ask James to merge my PR and add these updates to the live site.

![image](https://user-images.githubusercontent.com/82581364/153461621-52160b55-b929-4af4-a39d-a0069182b606.png)

**Comment by mstackhouse** [comment]
@rossfarrugia this looks fine to me. I like the emphasis that the point is adding value.
