### ISSUE TITLE
[BUG] timber and synthetic.cdisc.data are not getting OS-health reports

### ISSUE THREAD

**Issue by epijim** [pharmaverse/pharmaverse#115]
**Describe the bug**

See screenshot. If an os-health badge isn't created, it should simply not show a badge. Need to figure out why they are falsely getting an empty badge.

**Expected behavior**

If os-health fails, there should be no badge. If it works, there should be score breakdown on the click through

**Screenshots**

![image](https://user-images.githubusercontent.com/2760096/156723546-1b295704-5703-4d72-802d-767984fde412.png)

**Comment by rossfarrugia** [comment]
@epijim looks fine for logrx now (new name for timber) but not working for synthetic.cdisc.data and envsetup

**Comment by rossfarrugia** [comment]
@epijim to look into fixing.

**Comment by rossfarrugia** [comment]
These badges are now replaced on site by simplified metrics of CRAN version, GH stars and # of contributors: 

![image](https://github.com/user-attachments/assets/66a5fd56-15a6-41de-80a4-4f91524ee882)

Looks great @epijim 🤩
