### ISSUE TITLE
[Idea] Add Pharmacokinetics CTV

### ISSUE THREAD

**Issue by billdenney** [pharmaverse/pharmaverse#118]
**Describe your idea**
There is a list of CRAN task views.  Please add the Pharmacokinetics CTV to that list (https://cran.r-project.org/web/views/Pharmacokinetics.html).

**Additional context**
Disclosure:  I'm the maintainer of that CTV.

**Comment by rossfarrugia** [comment]
noted - and thanks for notifying! should get around to this next week
