### ISSUE TITLE
[BUG]  a hex is missing from main page

### ISSUE THREAD

**Issue by epijim** [pharmaverse/pharmaverse#119]
![image](https://user-images.githubusercontent.com/2760096/159473808-9914d47a-f40b-4d94-9e5f-591ca1283b50.png)

**Comment by billdenney** [comment]
Related to this, I think it would be helpful if the hex tiles linked to the packages themselves.  Inspecting the source to the page, there is an `<a>` link around the image, but it has no `href` attribute.

**Comment by rossfarrugia** [comment]
closing this one as now resolved and Bill's request is covered in https://github.com/pharmaverse/pharmaverse/issues/129 which is still open.
