### ISSUE TITLE
Issue and Pull Request Templates for Starter Packages

### ISSUE THREAD

**Issue by bms63** [pharmaverse/pharmaverse#121]
**Describe your idea**
Issue and Pull Request Templates for Starter Packages

**Additional context**
Since we all have a common theme of clinical reporting maybe package that come under our banner should be recommended to use common issue templates and common pull request templates like in admiral, admiralonco and now timber!

**Comment by rossfarrugia** [comment]
thanks @bms63 - i need to think on this one when we work on the admiral package extensions piece and the github template etc. my gut feel is that the convention of setting up issue/PR templates is a good practice that we want to recommend for new packages, but the templates themselves might vary.

**Comment by bms63** [comment]
I think they should be more generic for the template repo.  The leads can always remove them or modify them, but having something there is nice.  

Would be really nice if all admiral extension and related e2e packages had at least a similar feel to them for reporting bugs, requesting features, etc.

**Comment by rossfarrugia** [comment]
@bms63 check out my commit for this one - i think this is enough to share at pharmaverse level but shout if you have any other ideas.
