### ISSUE TITLE
[BUG] Incorrect information on SDTM e2eclincal ln27 

### ISSUE THREAD

**Issue by statasaurus** [pharmaverse/pharmaverse#122]
**Describe the bug**
At the moment the website says "removing/adding supplemental qualifiers from/to the parent SDTM domain (currently planned to incorporate into [metatools](https://pharmaverse.org/e2eclinical/metadata/))"
But it has already been added and released to cran. 

I am not sure what you prefer to do, but we either need to link to metatools here or add the fact this is possible with metatools to the metadata section of the website.

**Comment by rossfarrugia** [comment]
now resolved on the site
