### ISSUE TITLE
FAQs for lawyers and Leadership

### ISSUE THREAD

**Issue by bms63** [pharmaverse/pharmaverse#124]
**Describe your idea**
Lots of questions come up around open source and IP.  Be great to collate FAQ on the main site that we can send people to for common questions around these issues

**Describe alternatives you've considered**
NA
**Additional context**
NA

**Comment by rossfarrugia** [comment]
@bms63 any suggestion of what you'd add to this page https://pharmaverse.org/contribute/lead/ ?

**Comment by bms63** [comment]
Hey Ross.  I was more thinking of a separate FAQs for folks wanting to address questions that lawyers and leadership bring up when wanting to use pharmaverse packages or create a pharmaverse package.  

For example, 

- What is Open Source and what does that mean for my company?
- Patent rights and R packages
- Licenses (Apache versus MIT versus GPL).  
- Can company Y sue me for using their open source package, etc.  

Maybe it fits into the [lead](https://pharmaverse.org/contribute/lead/) page, but I was thinking more for just general people and not ones leading a package extension.

Also, happy to just drop this topic.  Someone just had questions around this stuff and was asking if we had any reference materials.  I usually just refer to this - https://r-pkgs.org/license.html

**Comment by rossfarrugia** [comment]
@bms63 sounds like you're looking for the guidance that will come out of this new PHUSE WG: https://phuse-org.github.io/E2E-OS-Guidance/. You can add ideas here https://github.com/phuse-org/E2E-OS-Guidance/discussions/1 for such topics you'd like to see covered. I think all of those you bulleted are already noted there. 

It's easy to think of pharmaverse site as the place to put everything around open sourcing but in reality this is just one effort for curating e2e R packages for clinical reporting, whereas more general industry open sourcing guidance like this goes beyond the pharmaverse scope and has much wider applicability.
