### ISSUE TITLE
Reports from diffify

### ISSUE THREAD

**Issue by bms63** [pharmaverse/pharmaverse#127]
**Describe your idea**
A link to the most recent version of the package comparing against the previous version.  Can leverage the diffify report to our advantage.  https://diffify.com/R/admiral/0.6.3/0.7.0

**Describe alternatives you've considered**
![image](https://user-images.githubusercontent.com/10111024/172170585-569bcddd-71c2-4aad-900c-7634eec91bd9.png)

**Comment by rossfarrugia** [comment]
Any thoughts on this @MichaelRimler @mstackhouse @skalappu @epijim? could be something we add to https://pharmaverse.org/nonpharma/?

**Comment by mstackhouse** [comment]
The link to the latest changes I think would be quite interesting, but might be hard to implement?

@rossfarrugia It could be useful in nonpharma - but diffify isn't a _package_ itself. When I was checking it out, I didn't find any source code. Has anyone else found the source?

**Comment by MichaelRimler** [comment]
If it's not open source (even if not permissively licensed), then it's difficult to incorporate into any 'validation' assessment, I presume. Eg, if we confidently know the incremental changes from release to release, then we only have to trust those changes. But if we don't 'trust' the package serving up the report of incremental changes, then it's harder. 

We can use, but not in a GxP documentation perspective. 

At some point, could we engage the package author?

**Comment by rossfarrugia** [comment]
Good points! When I reflect more on this I'm not really sure where it would go on our site, as its not open source and not a package. It's just a useful R resource. To me that's beyond scope of pharmaverse - we are not here to curate everything that could possibly be of use across R or our site would become unmanageable and the main things we want to share about clinical reporting open source packages would get flooded out. I vote we close this one with no action, as Ben already shared the useful resource with our community via Slack. I think that's where we should continue to share things like this in future, but in the general chatroom, so catches a wider audience than admiral users only.
