### ISSUE TITLE
admiral 0.6.3 still showing on website

### ISSUE THREAD

**Issue by bms63** [pharmaverse/pharmaverse#128]
**Describe the bug**
admiral 0.6.3 still showing on website

**To Reproduce**
NA

**Expected behavior**
admiral version 0.7.0 should show now

**Screenshots**
admiral 0.6.3 still showing on website

**Additional context**

**Comment by bms63** [comment]
![image](https://user-images.githubusercontent.com/10111024/172173192-62ba43db-81cc-47f1-a546-8111a49857eb.png)

**Comment by bms63** [comment]
Nice! I've noticed that our OS Health scores and riskmetrics score have decreased.  

The OS Health metrics are interesting as I was reading through the vignette and I like that level of detail.  Is it possible to have a report on that and how to mitigate negative score...right now it just takes me to everyone's information.

The riskmetrics takes me to a dashboard that doesn't make sense to me.    

![image](https://user-images.githubusercontent.com/10111024/172249185-e687ea2e-50c5-42a8-8b4a-cff270dc4382.png)

**Comment by rossfarrugia** [comment]
Probably something related to https://github.com/pharmaverse/pharmaverse/issues/116 but will let @epijim reply.

**Comment by rossfarrugia** [comment]
closing as resolved now but to Ben's point i added https://github.com/pharmaverse/pharmaverse/issues/146
