### ISSUE TITLE
Hex Stickers supposed to linked

### ISSUE THREAD

**Issue by bms63** [pharmaverse/pharmaverse#129]
**Describe the bug**
I would think these hex stickers would take me to the respective package github.  They are clickable, but they just refresh the page

![image](https://user-images.githubusercontent.com/10111024/172724279-33696759-355c-41ea-9a7b-288e3b226533.png)

**Comment by rossfarrugia** [comment]
@epijim i think we discussed this before and decided not to but i forget the reason?

**Comment by parmsam** [comment]
I agree with this. Was going to create an issue for this. The stickers change colors on mouse hover, so I would expect them to redirect to the Github repo or CRAN page on click.

**Comment by rossfarrugia** [comment]
@epijim will look into this

**Comment by rossfarrugia** [comment]
Also @epijim reminder to replace {rtables} with {envsetup} for more variety.

**Comment by rossfarrugia** [comment]
@MichaelRimler has an idea to replace the 6 hexes with a more complete visual representing the pharmaverse - he'll open this up to our community to volunteer ideas. so with this in mind i'll close this issue and we can replace with a new one to add whichever image is chosen.
