### ISSUE TITLE
Add explanation of the badges/scores

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#146]
add explanation for the badges, e.g. OS health and contributors etc to explain how scores are derived

**Comment by rossfarrugia** [comment]
@mstackhouse i queried this one with James from the email you sent the other week and if you click on OS health badge next to any package it opens up the explanation https://openpharma.github.io/os-health.html. Does the first Context paragraph there explain OK? Is it the naming that is the issue, e.g. would something like "OS Activity" be better?

**Comment by mstackhouse** [comment]
@rossfarrugia 

> if you click on OS health badge next to any package it opens up the explanation

The problem is a lot of people just won't do that. And there's a similar problem to here as riskmetric, where an overarching score is missing context of what is ultimately qualitative information. These scores are easy to bias into "bad score = bad package". 

OS Activity would be a better name the OS Health because 'Health" definitely reinforces the "bad score = bad package" paradigm. The first paragraph needs to be more explicit. Something like:

> OS Activity measures active development of a package by looking at metrics such as median issue age or inactivity, contributor participation throughout the package repository lifespan, commit frequency and recency. It's important to not consider this as a metric of quality, but as part of your decision making process for using a package based on your needs. 

> For example, some packages at a stable point are not updated frequently, as there is no required maintenance and no planned feature additions - but they are still robust, reliable packages. Furthermore, remember that data may not be perfect. Some packages are migrated to GitHub after internal development and git histories are not included, and in other cases GitHub data may simply be imperfect.

**Comment by rossfarrugia** [comment]
works for me! will try find how to get this updated as its external to pharmaverse site and this repo.

**Comment by MathieuCayssol** [comment]
https://openpharma.github.io/os-health

Issue solved ?

**Comment by rossfarrugia** [comment]
@MathieuCayssol the new OS Activity page looks good to me, but on pharmaverse site the badges still show as OS Health e.g. see https://pharmaverse.org/e2eclinical/tlg/ - any chance you could take a dig to see if you can find the reason? I think its because I just need to re-render the site and then these should fix, but shout if you spot any other potential reason.

**Comment by MathieuCayssol** [comment]
Where do you get the data from ? 

Because from my side, in this csv uploaded on AWS (https://openpharma.s3.us-east-2.amazonaws.com/badges.csv), the link has been updated.

**Comment by rossfarrugia** [comment]
@MathieuCayssol - the same: https://openpharma.s3.us-east-2.amazonaws.com/badges.csv

**Comment by rossfarrugia** [comment]
looks good on our side now @MathieuCayssol in develop branch, so pushing it through to the site now!
