### ISSUE TITLE
Update our R-universe to match latest package list

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#148]
https://pharmaverse.r-universe.dev/ui#packages

**Comment by rossfarrugia** [comment]
@cicdguy as discussed great if we could automate this maintenance from source files at https://github.com/pharmaverse/pharmaverse/tree/main/data/packages

**Comment by dgrassellyb** [comment]
@cicdguy  I started working on this issue, but there is a problem when I am trying to push with pharmaverse-bot's credentials (403 error) see logs here: https://github.com/pharmaverse/pharmaverse/actions/runs/4304918392/jobs/7506623807 , it seems weird because I can see pharmaverse-bot directly on pharmaverse organisation

**Comment by dgrassellyb** [comment]
Ok perfect I'll let you know :) also a question it seems that there are not every packages on pharmaverse -> data -> packages (if you take for example this one:
 {
    "package": "uniCATE",
    "url": "https://github.com/insightsengineering/uniCATE"
  })
  I guess I should update pharmaverse repo adding more yaml files ?

**Comment by rossfarrugia** [comment]
@dgrassellyb no, pharmaverse is a collection of chosen packages from a variety of GH orgs. we dont automatically include all from insightsengineering for example.

**Comment by rossfarrugia** [comment]
@dgrassellyb - Michael R (@MichaelRimler) spotted some packages are on the r-universe page but not from our pharmaverse package list, e.g. r2rtf. are you ok to take another look please at this one? let me know if unsure.

**Comment by dgrassellyb** [comment]
@rossfarrugia can I close it ? :)

**Comment by rossfarrugia** [comment]
done - thanks Daphne!
