### ISSUE TITLE
{ViridisLite} reference & logo need changing

### ISSUE THREAD

**Issue by sophie-gem** [pharmaverse/pharmaverse#149]
Apologies if this has already been identified - but I couldn't see an issue for it open (and it still looks to be the same on the development version of this page). So thought I'd mention it.

![image](https://user-images.githubusercontent.com/90790226/191955158-12bc91c6-6a5e-4b1f-b8b8-75835196b9d8.png)

There is a typo in the title of the package - it is called `viridisLite` as opposed to `gviridisLite` and also the logo (see red circle in above screenshot) is currently showing the {gt} package logo as opposed to the {viridisLite} logo.

**Comment by rossfarrugia** [comment]
thanks @sophie-gem - will try and fix later this week
