### ISSUE TITLE
tidyCDISC to be included?

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#155]
To be decided by: TLG and interactive tools WG

From Aaron Clark: In August, our dev team got {tidyCDISC} v0.1.0 published on CRAN and I’ve outlined and started to work on a fairly aggressive roadmap for our next major release. As such, we’d love to have some fellow collaborators from the pharmaverse join in the effort with us. I think the package fits nicely into the end-to-end clinical pipeline since it offers automatic table generation, exploratory visuals, and patient profiles from ADaM. But I would love to hear your thoughts.

**Comment by epijim** [comment]
Close as duplicated by #194 (and discussion is happening on the other issue)
