### ISSUE TITLE
Idea: A way to show package maturity & industry adoption level

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#169]
**Describe your idea**
Idea from @epijim and the Tech/Templates WG: can we make clearer which packages are more experimental and which are well adopted by numerous companies/being used in filings etc.

**Additional context**
The data for this could come from the R Adoption WG we're kicking off across 10 companies next year.

Could add extra metadata fields to the package yml files, and could bring this into new badges to give an easy way to show this on the site for each package.

FYI @nicholas-masel

**Comment by NNaikp** [comment]
This sounds like a great idea!
I imagine you could have something like a lifecycle.pharma package and also display these stats on the webpage.

**Comment by rossfarrugia** [comment]
Me and @epijim discussed this today and we've backtracked on this idea as we feel an extra badge would cause confusion versus the package version numbers where we already know that 1.0.0 denotes a greater level of maturity. Plus calling something that's still on the 0.x.x like xportr as "experimental" might put off companies adopting, even though it is relatively stable and it does the job well. For packages which are truly experimental we could add this in the text on our site like done for datasetjson:

![image](https://github.com/pharmaverse/pharmaverse/assets/82581364/956c6757-3a7d-4df5-8469-d4c7030f236d)


Please add comments if anyone disagrees.
