### ISSUE TITLE
e2e Clinical page: include all packages on one page

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#17]
https://pharmaverse.org/e2eclinical/ - for this page do you think we could try at first with including all the packages with high level descriptions here, rather than having sub-pages for each category like https://pharmaverse.org/e2eclinical/sdtm/ ?
I’m imagining something like https://www.tidyverse.org/packages/ where you still have easy to navigate contents you set up on the left hand side for the categories (I would suggest: General, SDTM, ADaM, TLG-execution, TLG-templates, TLG-orchestration, Interactive Display, eSub, Validation), but you can easily scroll through all of the package list then in one go.

**Comment by rossfarrugia** [comment]
Also page needs formatting updates to make the text look better aligned with the logos

**Comment by epijim** [comment]
Hey @rossfarrugia - is it ok how I organised it as of today. Wanted to break it down to improve load times, and help us try and make each section a bit more informative (e.g. adding background info, and at some point I guess the 'curation' content will need to be added).

**Comment by rossfarrugia** [comment]
@epijim yeh makes sense with the load times and i really like how you've organised this.
few minor spots:
- ggplot2 is under the TLG page and the other useful packages - would you have it in both? i was imagining only the nonpharma 
- when will nest open source? looks confusing to have these closed source packages at the top, instead of under an “Upcoming packages” section more at the bottom like done for Oak / SDTM page
- "regultory" -> "regulatory" typo on eSub page

**Comment by epijim** [comment]
> ggplot2 is under the TLG page and the other useful packages - would you have it in both? i was imagining only the nonpharma

Yeah - my thinking was 'plotting' is pretty much solved, so it was weird to have a gap. Maybe if we leave it in, but add some text? added: 

![image](https://user-images.githubusercontent.com/2760096/146252621-6a57944e-ac92-4169-b86d-da05323fbe52.png)

> when will nest open source? looks confusing to have these closed source packages at the top, instead of under an “Upcoming packages” section more at the bottom like done for Oak / SDTM page

Oak is just an internal package right now though - Nest is shared between 4 companies and a vendor. Nest is also about to open source, and chunks of it are open source already (e.g. rtables, thevalidator, staged.dependencies, etc)

> "regultory" -> "regulatory" typo on eSub page

fixed

**Comment by rossfarrugia** [comment]
@epijim thanks - fine with all replies. as long as nest is soon to open source it's fine. i just don't want this to perceived as us trying to put the Roche offerings on the top (even when they're not yet open to all). it'd be great if it could be targeted to be open sourced before PHUSE US Connect 2022 as we want to make this a pillar of the workshop and will be way more attractive at that stage if companies don't need to go through any feasibility agreement contracts etc to get their hands on it.
