### ISSUE TITLE
Idea: bitesize intro video on homepage  

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#170]
**Describe your idea**
Idea from Jaime: There's a lot to read on our site so maybe a bitesize 2min video would help to quickly digest an intro to the pharmaverse (could also add to our youtube channel)

**Comment by bms63** [comment]
Sadchla was just talking about this in our xportr meeting today!!  @sadchla-codes

**Comment by rossfarrugia** [comment]
@MichaelRimler FYI of this idea as well for the pharmaverse website front page, which maybe could be shown alongside the new visual in the place of the current 6 hexes.

**Comment by rossfarrugia** [comment]
i'm going to close this one - we never got around to it and since then we updated the front page now with nicer visuals anyway so a video wouldn't really fit in. i feel like pharmaverse already has decent exposure now and its easy enough from our website to understand what we're trying to achieve,.
