### ISSUE TITLE
E2E Examples should have sections in TOC

### ISSUE THREAD

**Issue by bms63** [pharmaverse/pharmaverse#171]
**Describe your idea**
E2E Examples should have sections in TOC to help increase navigation options

**Describe alternatives you've considered**
None considered

**Additional context**
![image](https://user-images.githubusercontent.com/10111024/207152739-47bcc83c-369e-4c1b-ab86-966cd7f58f9b.png)

**Comment by rossfarrugia** [comment]
Moved issue to the examples site repo. Good idea!
