### ISSUE TITLE
pharmaverse blog posts

### ISSUE THREAD

**Issue by bms63** [pharmaverse/pharmaverse#173]
**Describe your idea**
bi-weekly short blog posts showcasing how to use different pharmaverse package functions.  I'm particularly interested in showcasing admiral functions, but open to others as well.

**Describe alternatives you've considered**
None
**Additional context**

Mostly likely develop as a standalone quarto based website that can be linked at the top like the examples.  I'm very keen in posting this stuff on Linkedin to continue to drive interaction and get our name out there.  I think this will also be good for people looking to help out but unsure how to contribute.  

![image](https://user-images.githubusercontent.com/10111024/210658344-05633b21-c259-4381-a8f3-079ff33ad32f.png)

**Comment by rossfarrugia** [comment]
@skalappu @MichaelRimler @mstackhouse an idea to discuss at a future council call.

thanks Ben!

**Comment by bms63** [comment]
Just for reference.  I really enjoy Steven Paul Sanderson's blog posts on their packages in their `healthyverse`, which they post on LinkedIn.  They are short and informative and always have readable code snippets with examples. 

https://www.linkedin.com/posts/spsanderson_histograms-binning-data-activity-7018575712777355264-Oy-o?utm_source=share&utm_medium=member_desktop

![image](https://user-images.githubusercontent.com/10111024/211663810-17a2275a-3a5b-4084-81ea-ccac63d793f9.png)

**Comment by rossfarrugia** [comment]
@skalappu @MichaelRimler @mstackhouse @NNaikp - our next council meet agenda i saw is quite packed, so how about we discuss thoughts for this proposal here? 

I also tag our Tech/Templates WG members too in case they want to comment @nicholas-masel @statasaurus @epijim.

My personal take on this is great idea but I would vote that LinkedIn posts from the pkg devs (and sharing them on the LinkedIn pharmaverse group) would be the best route for this. My reasoning for not including this in the website would be that we already heard feedback on the amount of content people have to read in our website and all the many links we offer, so its already becoming overwhelming for new folks visiting for the first time. So frankly I'm not sure how many people would click and open the "blog" section. They're more likely to see this on LinkedIn if they follow our group or the devs of the packages they use. Also my hope would always be that such useful code snippets are always included on the package website functional documentation itself. So whilst these posts offer useful reminders or help notify users of a nice feature they may not have seen before, this shouldn't be the only source they can find the info.

**Comment by NNaikp** [comment]
Personally, the route Ross is describing, is how I found and followed most of you guys (yourself included @bms63 😄  ).
If the landing page is getting an overhaul anyway to highlight the community side more then a middle way could be to have a so-me ticker on #pharmaverse from LinkedIn somewhere on the page together with the contributions to repos.
Just looking at the existing posts with this hashtag there are a lot of package releases/updates and upcoming events.

**Comment by rossfarrugia** [comment]
that's a nice idea Ari - like it! will add a note on this to the other discussion on the homepage to link these.

**Comment by bms63** [comment]
Hi @NNaikp!!  

blog posts on linked in sounds good and I understand on keeping the noise down on the main site.  

If okay, I might just make a blogdown site anyways as it will be easier to code and showcase with the screenshots and code snippets for the linked in post.  The posts are just meant to get into people's Linkedin feeds to be like --- hey you!  You need to do X for your ADaMs ... well we got you covered with `derive_var..., restrict, consolidate, etc`!  

Also, I think this gives people an opportunity to help contribute without needing to be a serious R package dev.  

@sadchla-codes seemed very interested in the blogs.

**Comment by NNaikp** [comment]
> If okay, I might just make a blogdown site anyways as it will be easier to code and showcase with the screenshots and code snippets for the linked in post. The posts are just meant to get into people's Linkedin feeds to be like --- hey you! You need to do X for your ADaMs ... well we got you covered with `derive_var..., restrict, consolidate, etc`!

You most definitely should still do this! 🚀

**Comment by bms63** [comment]
Blog launched!
