### ISSUE TITLE
Top Menu Bar:  Change EXAMPLE to e2e Examples

### ISSUE THREAD

**Issue by bms63** [pharmaverse/pharmaverse#174]
**Describe your idea**
Change EXAMPLE to e2e Examples or at least Examples.  The all CAPS is a little strange to look at :) 

![image](https://user-images.githubusercontent.com/10111024/211877343-ec5a23e0-0306-4187-a9fc-116f3070a22a.png)

**Comment by rossfarrugia** [comment]
ok will use Examples - as someone commented before that e2e is not accessible to all as not immediately clear end-to-end is meant
