### ISSUE TITLE
defineR to be included under eSub page?

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#177]
Someone shared this with me on LinkedIn for consideration into pharmaverse: https://cran.r-project.org/web/packages/defineR/index.html

To be reviewed by Tech/Templates WG

**Comment by epijim** [comment]
I don't think this package could be considered without a clear pointer to the location of where the code is written? 

Could we ask for the github/gitlab repo, then consider them?

**Comment by rossfarrugia** [comment]
https://github.com/dbosak01/defineR

**Comment by rossfarrugia** [comment]
**Decision from Tech/Templates WG:**
We do think some companies could benefit from a define.xml creator, but we felt that alone this doesn't consitute sufficient benefit for a new package under pharmaverse. Also each company may have their own spec formats (which something like {metacore} helps to harmonize), so our preferred strategy would be to add the feature to {metacore} so for the companies that don’t already feed in define.xml here they’d be able to create one from the metacore objects.
Action: @statasaurus to discuss with the team behing {defineR} to see if there's willingness to join forces with {metacore}, and to get this working for latest version of define.
