### ISSUE TITLE
Council page - clarify sentence

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#185]
On Council page https://pharmaverse.org/contribute/council/, we have a confusing sentence: “The Council does not accept organizations into the pharmaverse, but any organization can be a member - any individual can contribute.”

What was intended here was to mean: "the Council is not adjudicating applications for organizations or individuals into the pharmaverse. Anyone can contribute. That is different from membership into the Council, which does require a decision to accept."

@MichaelRimler should we delete this sentence now, given we now have other pages like https://pharmaverse.org/contribute/ic/ showing the other ways people can contribute? I think we authored this prior to having those other pieces worked out. Or alternatively, let me know if you have an alternative sentence you'd like to replace it with?

**Comment by MichaelRimler** [comment]
@rossfarrugia : Agree and sentence can be deleted.

**Comment by rossfarrugia** [comment]
Also as part of this update we should add a link to where we store the council minutes now that we'll be openly publishing these from this year onwards.
