### ISSUE TITLE
Update landing page hexes

### ISSUE THREAD

**Issue by NNaikp** [pharmaverse/pharmaverse#188]
ref. the discussion on the pharmaverse slack.

And idea for the landing page hexes could be something like the below where you can see all packages in the pharmaverse and travel to the respective package docs (or a better place).

Internally, we have this on our R landing page:

![image](https://user-images.githubusercontent.com/85683724/217236902-d029e9b1-fb67-4ad8-a8d5-122cba3d4c2a.png)

**Comment by MichaelRimler** [comment]
Link this to Issue 189
https://github.com/pharmaverse/pharmaverse/issues/189

**Comment by epijim** [comment]
@NNaikp - do you have the code for this? we do the same thing for open sourced R packages 
![image](https://user-images.githubusercontent.com/2760096/217478284-6674c435-423a-4f5c-9161-aa629ddd7627.png)

**but**, we are writing it out as pngs (code is here: https://github.com/insightsengineering/hex-stickers/blob/main/README.Rmd#L75).

Earlier in that script, we do write out HTML, but not in a hex format (see the table under 'hex stickers': https://github.com/insightsengineering/hex-stickers).

Do you have code already to write the html as a hex? I'm sure it's totally doable, but if you have the code already to programmatically write the HTML, and you've already done the css, it would be awesome. If not - I guess we can take the hand coded HTML from the current page as a starting point, and convert that to be programatically created.

**Comment by epijim** [comment]
Overall though - I would love to have an R package that took hexes and spit out either a png (code is ready for that) or HTML (I don't have code yet, but maybe Novo do?). Saying an R package as this could be useful in many places beyond the pharmaverse website. 

Maybe a PR on this package? https://github.com/mitchelloharawild/hexwall

**Comment by NNaikp** [comment]
I talked with the developer for our wall and he had used some borrowed CSS honeycomb specifications (very similar to [this](https://codepen.io/adamriguez/pen/eRaXeq)) and then the HTML was quite simple to do. The HTML for the above looks like this:

```
<ul id="hexGrid">
  <li class="hex">
    <div class="hexIn">
      <a class="hexLink" href="NNpackages/NNBiostat">
       <img src="images/stickers/NNBiostat.png" alt=""/>
        <h5>NNBiostat</h5>
        <p>Load biostat and cran packages</p>
      </a>
    </div>
  </li>
  <li class="hex">
    <div class="hexIn">
      <a class="hexLink" href="NNpackages/NNR">
       <img src="images/stickers/NNR.png" alt=""/>
        <h5>NNR</h5>
        <p>Load biostat packages</p>
      </a>
    </div>
  </li>
 ...
</ul>
```

It shouldn't be too hard to make a function that creates this based on package descriptions. The only thing would be that the paragraph is shorter than the package title and was probably created by hand in our case.

**Comment by rossfarrugia** [comment]
Closing this issue in favour of https://github.com/pharmaverse/pharmaverse/issues/212
