### ISSUE TITLE
Add logic to handle packages with no hex sticker

### ISSUE THREAD

**Issue by epijim** [pharmaverse/pharmaverse#19]
Currently I manually made some packages using https://github.com/GuangchuangYu/hexSticker for those with no hex sticker.

This should be productionised into the cicd when site goes to prod.

This issue is a dependency to #3

**Comment by epijim** [comment]
Right now we are just inserting a special blank hex if there is no official one.

**Comment by rossfarrugia** [comment]
I'm going to close this as i don't think value add and it's been  open so long - we just use blank hexes in this case which is fine and we can choose not to add them to our new hex wall
