### ISSUE TITLE
Cover legal liability and disclaimers

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#193]
Add more to our website around legal liability (i.e. people take responsibility as users of these packages, and there is no mandate - everyone makes a choice of whether to use any selections of packages within or beyond the pharmaverse list).

Add following in red text to homepage:
_"Disclaimer: Anyone is free to choose any selection of pharmaverse recommended software or those from any other source, as there are many different pathways available. Being listed on our site gives no endorsement of the reliability of any code, it is up to you to assess suitability for your needs. Finally, before using any open source software you should always check the license."_

@MichaelRimler to the point made in your review comment, i think the above line on endorsement is the safest wording as our WGs won't necessarily ever test the "reliability" of code, i.e. we don't stringently go through unit tests for each function etc. Our inclusion criteria is more around how suitable packages are to be listed under pharmaverse and some good software dev best practices. I expect our user community then to test the reliability over time through usage and reporting bugs etc.

**Comment by epijim** [comment]
![image](https://user-images.githubusercontent.com/2760096/228526151-124061b3-6fe0-459e-af27-24e505e2b476.png)
 
and it's edited via 

![image](https://user-images.githubusercontent.com/2760096/228526192-9bb8b5fe-5452-4ba2-95dc-1e456ef8d7fc.png)


I didn't like the red, so would prefer to stick to just italics

![image](https://user-images.githubusercontent.com/2760096/228526257-043fe270-a8b8-4052-b4ea-ac28702cdf3a.png)

**Comment by NNaikp** [comment]
I would be happy with this for now

**Comment by epijim** [comment]
cheers - @rossfarrugia, I did this directly onto `develop`, so currently it will be merged next time there is a pr to prod.

**Comment by epijim** [comment]
changes to close this ticket were made in https://github.com/pharmaverse/pharmaverse/commit/938234ba95fe13ad6d2e4d6b2d24f546e6d7d62b

**Comment by rossfarrugia** [comment]
yeh i guess the red distracts from the text above. thanks @epijim - want to make a PR for this and i'll approve and merge so we can close out this one?

**Comment by MichaelRimler** [comment]
FWIW, I like the italics. Thanks for the improvements here.
