### ISSUE TITLE
[New package request]: `{tidyCDISC}`

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaverse/pharmaverse#194]
Related to #155

- [x] I have first considered whether there is already an existing pharmaverse package that could solve this need, or if I could combine forces with an existing effort to add my features to their existing package.

    * The closest package/ application to `{tidyCDISC}` would be the recently open-sourced `{teal}` suite of packages. Though, they offer some similar capabilities, they are vastly different in their approach and user experience, with the most notable being table generation. I'd argue each has something unique to offer end users, and there is room for both to thrive in the pharmaverse.

- [x] I confirm I have read https://pharmaverse.org/contribute/lead/ and my package follows the Inclusion Criteria for pharmaverse.

    * Note: [**this issue**](https://github.com/Biogen-Inc/tidyCDISC/issues/153) shows tidyCDISC meets the pharmaverse inclusion criteria. Happy to provide more info as needed.

### Name and description of package
`{tidyCDISC}` is a `{golem}`-based application that allows users to upload `ADaM` data and accomplish a myriad of exploratory data analyses. First and foremost: users can create custom tables via a user-friendly drag-and-drop interface, offering a low barrier to entry for non-programmers. It also offers a handful of useful modules to monitor and visualize population and individual patient trends through a study. The code used to generate tables via the drag-and-drop interface runs `dplyr` under the hood and can be exported as an R script for full reproducibility, running independently from the app. For a detailed walk through of the app, please watch our presentation at [Shiny Conf 2022](https://www.youtube.com/watch?v=0K8PCeKDbrI) or read through the ['Get Started' vignette](https://biogen-inc.github.io/tidyCDISC/articles/tidyCDISC.html).

### Category of package
TLGs

### Who is involved in developing/maintaining this package?
- License owner(s): Biogen Inc
- Maintainer: Aaron Clark
- Companies involved: Biogen Inc, Cytel

**Comment by rossfarrugia** [comment]
thanks @AARON-CLARK! Tagging the TLG and interactive tools WG (@mstackhouse @gorthis @statasaurus @telepath37) here to consider this request.

**Comment by AARON-CLARK** [comment]
Excellent @rossfarrugia 👍🏼. I know these 'pkg inclusion requests' were only recently streamlined into github issue templates, but wondering if you know a general expectation on timeframe for the assessment & review process? Thanks! Happy to provide more pkg info as needed.

**Comment by mstackhouse** [comment]
tidyCDISC is accepted and we can move to put it on the site!

**Comment by AARON-CLARK** [comment]
Hi, thanks all. I've updated our `README` with a [pharmaverse badge](https://github.com/Biogen-Inc/tidyCDISC#readme). I see the changes have hit the pharmaverse site too. Looks great!

I wanted to inquire about creating a public and private dev channel in the pharmaverse slack? It looks like I have permissions to do that, but wanted to check with you all if that's kosher? Thanks!

![image](https://user-images.githubusercontent.com/17878953/227957339-7c85a4f4-daef-479f-80b7-c01f82313d28.png)

**Comment by AARON-CLARK** [comment]
> Want me to post an announcement once you have the public channel ready @AARON-CLARK? just let me know if so, as only some of us have access to post in the announcements channel. or you could use the general-chat channel if you prefer to post.

Okay, @rossfarrugia - I've spent some time building out some resources in the new `tidyCDISC` [public slack channel](https://pharmaverse.slack.com/archives/C0513FF9LJ0/p1680182912549999). It's fair game to blast the `announcements` channel when you are ready. Thanks!
