### ISSUE TITLE
[New package request]: `{riskassessment}`

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaverse/pharmaverse#195]
Hi all,

Thanks for considering this new package request. I should state the `{riskassessment}` and `{riskmetric}` packages are on-going workstreams supported by the R Validation Hub and that `{riskassessment}` is a shiny app that extends the work of `{riskmetric}`. As such, you can expect a new package request from the `{riskmetric}` development lead soon.

Back to the template:

- [x] I have first considered whether there is already an existing pharmaverse package that could solve this need, or if I could combine forces with an existing effort to add my features to their existing package.

   *  `{riskassessment}` is quite unique. For additional details, see our repo's [Pharmaverse Inclusion Criteria Checklist](https://github.com/pharmaR/riskassessment/issues/445).

- [x] I confirm I have read https://pharmaverse.org/contribute/lead/ and my package follows the Inclusion Criteria for pharmaverse.

    * `{riskassessment}` meets all the requirements, except for the CRAN Acceptability. Is this a requirement? There seems to be a number of Pharmaverse packages not on CRAN such as {chevron}, {teal}, and {tidytlg} to name a few.

### Name and description of package
`riskassessment` is an R package containing a shiny front-end to augment the utility of the [`riskmetric`](https://github.com/pharmaR/riskmetric) package within an organizational context. `riskmetric` is a framework to quantify an R package’s “risk” by assessing a number of meaningful metrics designed to evaluate development best practices, code documentation, community engagement, and development sustainability. In it's current state, the app extends the functionality of `riskmetric` by allowing the pkg reviewer to:

- analyze `riskmetric` output without the need to write code in R
- contribute personalized comments on the value of individual metrics
- categorize a package with an overall assessment (i.e., low, medium, or high risk) automatically based solely on risk scores OR manually based on subjective opinions reviewer consensus.
- download a static reports with the package risk, metrics outputs, and reviewer comments, and more
- store assessments in a database for future viewing and historical backup
- user authentication with with admin roles to manage users and metric weighting

### Category of package
Validation

### Who is involved in developing/maintaining this package?
- License owners: R Validation Hub
- Maintainer: Aaron Clark
- Which companies are involved: Truly, all the companies that are members of the R Validation Hub. But those with the greatest influence are: R Consortium, Biogen, Cytel, GSK, Roche, Boehringer Ingelheim, Pfizer, Canary Medical, JnJ, Parexel, Merck

**Comment by rossfarrugia** [comment]
thanks @AARON-CLARK! Tagging the Technology and templates WG (@epijim @nicholas-masel @statasaurus & myself) here to consider this request.

**Comment by AARON-CLARK** [comment]
Excellent @rossfarrugia 👍🏼. I know these 'pkg inclusion requests' were only recently streamlined into github issue templates, but wondering if you know a general expectation on timeframe for the assessment & review process? Thanks! Happy to provide more pkg info as needed.

**Comment by rossfarrugia** [comment]
Lot of folks are out at PHUSE US currently so I'd expect to give 1-2 months for these. Sometimes it might be quicker, but depends on how debatable inclusion is and plus everyone here are volunteers giving their own time for pharmaverse. 

On a side note, would you be interested in joining any of our WGs?

**Comment by rossfarrugia** [comment]
@AARON-CLARK when i try the app i keep getting the following whenever i choose a package - is this a known issue?

![image](https://user-images.githubusercontent.com/82581364/227506347-2d6f0109-81a9-4903-9512-87116431df66.png)

**Comment by AARON-CLARK** [comment]
Whoops @rossfarrugia, that's embarrassing. So, we recently deployed `riskassessment v0.1.1` to shinyapps.io because the URL `cranlogs::cran_downloads()` uses (to track pkg downloads per month) was occasionally returning a 404 message, hence the modal you see above.

While we diagnose why shinyapps.io is lacking connectivity, you have two options to explore the app right now:
* if you were to [clone the repo](https://pharmar.github.io/riskassessment/index.html#installation) and run locally, the issue doesn't exist.
* I still have `v0.1.0` [deployed on shinyapps.io](https://rinpharma.shinyapps.io/riskassessment_v010) which doesn't check URLs for connectivity. Just know, `v0.1.0` doesn't have any of [these features](https://pharmar.github.io/riskassessment/news/index.html#riskassessment-011).

Either option is fine. I'll follow up when `v0.1.1` has a successful deployment on shinyapps.io. Again, my apologies for the trouble.

**Comment by rossfarrugia** [comment]
Thanks @AARON-CLARK - looks really cool! I knew of riskmetric before but the app was new to me. We're discussing this at a Tech/Templates WG meet next week and then will let you know if accepted.

One more question I had was how come for admiral we get the following:
![image](https://user-images.githubusercontent.com/82581364/227553514-085bbaa2-13e6-43ba-a184-d48ba857b418.png)

I did the obvious thing and just checked a package I'm most familiar with, but don't know why all the exported functions weren't found above from the namespace.

**Comment by AARON-CLARK** [comment]
> On a side note, would you be interested in joining any of our WGs?

Perhaps! How do I learn more about the existing working groups? [Here](https://pharmaverse.org/contribute/wg/)?

**Comment by rossfarrugia** [comment]
Yes that's right - for the TLG one I need to update the mission statement but its basically just "_To govern the inclusion of tables/listings/graphs and interactive tool packages_" - as we don't want to repeat efforts from RTRS from R Consortium. Happy to take a call sometime and chat if you'd like.

**Comment by AARON-CLARK** [comment]
> I did the obvious thing and just checked a package I'm most familiar with, but don't know why all the exported functions weren't found above from the namespace.

That's how I operate too! Always checking pkgs I've contributed to. 

The issue you note here is currently a [work-in-progress](https://github.com/pharmaR/riskassessment/issues/428#issuecomment-1440373043). `{riskmetric}` is designed to build metrics & scores based off an the environment of the machine running the code. Because our app doesn't have a library of pkgs installed, it is running a very cran-centric approach via `riskmetric::pkg_ref(..., source = "pkg_cran_remote")`. This also ensures all deployments (locally or on RSConnect or shinyapps.io) match. Unfortunately, not all `{riskmetric}` metrics jive the remote CRAN approach. Thus, we'll soon be switching over to a new approach where we can point to an installed library of pkgs, allowing `riskmetric` to pull metrics with `source = "pkg_install"`.

If you were to run this code on your local machine where `admiral` is installed, you'd get a score of 1 for the `export_help` metric:
```
library(dplyr)
library(riskmetric)

packageVersion("riskmetric") # v0.2.0
packageVersion("admiral") #v0.9.1

assessed <- "admiral" %>%
  pkg_ref() %>%
  as_tibble() %>%
  pkg_assess()

assessed %>%
  pkg_score() %>%
  select(export_help)

> export_help
> 1 
```

**Comment by rossfarrugia** [comment]
Got it - thanks @AARON-CLARK!

**Comment by rossfarrugia** [comment]
Hey @AARON-CLARK, we discussed this at last Tech/Templates WG meet and here's our thoughts...

We’d be happy to have riskassessment & riskmetric listed on pharmaverse given the strong industry collaboration and co-development that has been displayed here, which is what pharmaverse is all about lifting up. We did have one request to your team though for consideration… would you be willing to add something on your homepages by way of a disclaimer or guardrail for users to make clear that these tools act only as a supportive measure for informing decision making around validation, as being sure of the robustness and reliability of any software may often require deeper inspection. There was a general concern from our WG that it would be easy for a developer to gamify this just to get a good score without meaningfully proving the true quality of a package, just like can be achieved with any other such metric like test coverage scores, and maybe those criteria that are more testable aren't always what dictates a good package.

_@nicholas-masel @statasaurus shout if i misrepresented anything!_

**Comment by AARON-CLARK** [comment]
> these tools act only as a supportive measure for informing decision making around validation, as being sure of the robustness and reliability of any software may often require deeper inspection.

👍🏼 Thanks for your thoughtful consideration & I have no qualms adding that sentiment to `riskassessment`'s README file.  When I present these tools, I always frame our risk-based approach as a "suggested layer to a multi-layered validation workflow". However, I did want to ping the `riskmetric` lead @emilliman5 to see if he's kosher with that addition to the `riskmetric` repo? FYI - Eric is OOO this week.

I did a quick skim of `riskmetric`s [README ](https://github.com/pharmaR/riskmetric#background) and found a phrase that jives with that point of view, but could probably could be more explicit.

> This package serves as a starting point for exploring the heterogeneity of code quality, and begin a broader conversation about the validation of R packages.

Thanks!

**Comment by rossfarrugia** [comment]
Thanks @AARON-CLARK - will try get these added to the site in next couple of weeks working around Easter holidays and then you can add the [badges](https://pharmaverse.org/contribute/badges/) to the readme and happy to do announcement again etc like for `tidyCDISC`. I assume you guys wanted `riskmetric` on too right? I know you mentioned a request would come for that separately, but we couldn't really review/accept one without the other.

**Comment by rossfarrugia** [comment]
Thanks! Some replies:
1. Looks reasonable to me - i spotted a couple of typos and the other WG members could comment or make an issue if any other suggestions. Appreciate the quick action!
2. We have a general `#validation` channel on our pharmaverse Slack as we felt this will always end up a question for R newcomers, so you could maybe just post the message and link there to save setting another channel. 
3. Good spot! Looks like we already had this on our list from our past considerations in the early days but we never got it to the Validation page for whatever reason 😕

**Comment by epijim** [comment]
Thanks for the dialogue above. @AARON-CLARK - would it make sense to mention the R Validation Hub does have an implementation effort, which would be where this is deployed within that multi-prong approach that includes human review?

Referring to this: https://github.com/pharmaR/regulatory-r-repo-wg

**Comment by epijim** [comment]
A related note is that we actually use riskmetric as an indicator on pharmaverse.org. e.g. 
<img width="612" alt="image" src="https://user-images.githubusercontent.com/2760096/230598396-a7258b97-723d-49bb-9354-02aef3a9b52f.png">

**Comment by rossfarrugia** [comment]
@AARON-CLARK your badge is now available https://pharmaverse.org/contribute/badges/ 🥇 😉
