### ISSUE TITLE
Consider adding TLG catalog link as it offers helpful examples

### ISSUE THREAD

**Issue by perttolj** [pharmaverse/pharmaverse#198]
Hi, the NEST TLG catalog has been recently open sourced here:
https://insightsengineering.github.io/tlg-catalog/
It contains a growing number of examples how to build tables, graphs and in the future listings. For any teal/tern users (or potential users) it would be a valuable resource.
Would it be possible to place that link in the TLG page
https://pharmaverse.org/e2eclinical/tlg/
For example as follows:

-------------------

A Tables, Listings, and Graphs Catalog with many examples is available here:
[TLG Catalog](https://insightsengineering.github.io/tlg-catalog/)

-------------------
Thanks!
Kind regards, jp

**Comment by rossfarrugia** [comment]
@mstackhouse @telepath37 please discuss with the TLG WG and let me know if you agree to add this

**Comment by telepath37** [comment]
@mstackhouse I sent a message on the slack channel to get people's awareness. I think this TLG-Catalog is a great companion for people to try out tern/rtables. I'd support to add it to the pharmaverse TLG webpage. Let me know your thoughts. Thx!

**Comment by pawelru** [comment]
Hey @mstackhouse is there any updates on this? We recently push some nice enhancements to the website and I feel it is definitely ready to be advertised further.

**Comment by rossfarrugia** [comment]
No reply from TLG WG, but I will add this as it is a good companion to help ease the usage of these packages already included on pharmaverse site.

**Comment by mstackhouse** [comment]
Just to confirm - there's no issues here. We should likely similarly have a link out to the [RTRS book](https://rconsortium.github.io/rtrs-wg/)

**Comment by rossfarrugia** [comment]
> Just to confirm - there's no issues here. We should likely similarly have a link out to the [RTRS book](https://rconsortium.github.io/rtrs-wg/)

Absolutely - will do for this issue https://github.com/pharmaverse/pharmaverse/issues/183
