### ISSUE TITLE
Website homepage: Replace the current hex visuals with new packages and people displays

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#212]
The major visual of the page will show 2 different side by side images:

1. an **alphabetically/random ordered** hex wall automatically updated with all our packages like James/Ari discuss [here](https://github.com/pharmaverse/pharmaverse/issues/188) (and if you click a hex it takes you to the package GH repo) 
2. some kind of interactive visual nodal network like [this](https://codepen.io/NNaikp/pen/XWPNVXV) displaying all of the contributors and how they overlap with the packages they contribute to (and if you hover over any you get their GH handles so individuals see their names). 

Example:
![image](https://user-images.githubusercontent.com/82581364/227888804-97d5bcda-ec9a-4abf-be16-5959165dca04.png)

Then remove the “How can I get involved?” FAQ, which is now covered above.

@NNaikp FYI to your question in the review doc, here's where you find the packages: https://github.com/pharmaverse/pharmaverse/tree/main/data/packages

@MichaelRimler @nicholas-masel  - I propose we go with just these displays first and not anything company-level, as I want to show pharmaverse is open to all regardless of which company you work for, and I'm also worried we'll make the homepage over-busy .

**Comment by rossfarrugia** [comment]
Under packages hex wall, we could also move the line from our FAQ to here about how to request a package added to the pharmaverse, e.g.:

"If you have a package for pharmaverse inclusion, raise an issue [here](https://github.com/pharmaverse/pharmaverse/issues) and use _"New package request"_ template."

**Comment by rossfarrugia** [comment]
Also at the bottom of the homepage now we could just list out the council and WG contributors, and lose the long list of all code contributors as it’d be covered in the visual above

**Comment by NNaikp** [comment]
I'll take a stab at the hexwall first and see if I can "functionalise" the html/css we have internally for it

**Comment by NNaikp** [comment]
@rossfarrugia @epijim you can see a version of the hexgrid [here](https://codepen.io/NNaikp/pen/KKxYZad).
Any preference for order of appearance? Currently and R-script generates the html based on the yaml files we have available.

**Comment by rossfarrugia** [comment]
Those "Upcoming packages for consideration" are roak, datacutr, tidytlg and chevron just so you have them.

**Comment by MichaelRimler** [comment]
Like. Like. Like.

Also - we could add placeholder empty hexes to show room to grow + make for nice geometry when the number of packages is awkward (like 17). But that might be challenging to automate - you'd probably have to do some algebra :)

**Comment by NNaikp** [comment]
I've updated the [example](https://codepen.io/NNaikp/pen/KKxYZad) to display the main admiral package, the packages currently included and given the hover panel the primary color from our website.

@MichaelRimler This is doable, but you would need some JS skills I don't have 😅 
It is already using the flex-wrap CSS property such that it wraps based on the size of the window. 
For the placeholder hex, we could create a sticker that states: "Your package here?" which is then always placed at the end of the wall?

**Comment by MichaelRimler** [comment]
@NNaikp Let's walk before we run. What you have done is awesome - we can ignore my 'nice-to-haves' for the time being and see how the existing update feels for a bit. :)

**Comment by statasaurus** [comment]
@NNaikp Ross just showed me the sample website and I noticed the package hover over might not have quite enough contrast between the text and hover color. [This](https://www.a11yproject.com/checklist/) is a nice checklist of what makes an accessible website. But basically you want a contract ratio of text to background to be between 3.0:1 to 4.5:1

**Comment by NNaikp** [comment]
@statasaurus Thank you for sharing the link! I haven't built many websites, so really nice to have a checklist for it 👍 
For the color then I was playing around with the gradient of our primary color to see how it looked - if you look now you see the primary color without gradient which hits a contrast of ~4:1 (which looks nicer).

I'll have to check the hover font-size and weight tough - so I'll use the checklist for that 😄 
Any other comments are very welcome! I'll try and keep the pen updated.
BTW it is not sassified yet as it will be when i'll incorporate it into the site and I'm also missing to align the "Packages"/"People" 😅

**Comment by epijim** [comment]
@NNaikp - would you be keen to move the script into an R package? 

I think it's awesome for the site, but really want to be able to make these wall with other groups of packages (e.g. we also currently make a PNG wall of Roche packages, and want a way to also do HTML.

I'm guessing it's also based on this post? http://web-tiki.github.io/responsive-grid-of-hexagons/ I (stupidly forgetting to check this issue), hacked together a script for the Roche R packages as well using I think the exact same post 😆 

Maybe it could be a package focussed on families of packages (e.g. runiverses 😆 ), which can:

- arrange hex stickers into hex walls
- generate contributor info (we have this code already in the pharmaverse, so it's just a gh wrapper)
- create contributor wall and network plot

Second two are more wrappers.

Does that make sense? What you did is very cool - and can't wait to see it in the site + elsewhere 👍🏽

**Comment by nicholas-masel** [comment]
Should we apply this update to the pharmaverse github landing page image as well?  I'm not sure who owns this part, maybe @epijim @rossfarrugia.

https://github.com/pharmaverse.

**Comment by rossfarrugia** [comment]
The github landing page is just a screenshot for now (low tech!) so wouldn't be dynamic like this, unless @epijim or @NNaikp has any clever ideas. it's populated by a markdown file (https://github.com/pharmaverse/.github/blob/main/profile/README.md)

**Comment by rossfarrugia** [comment]
@nicholas-masel i updated the visual at https://github.com/pharmaverse for now to remove the hexes as you made a good point that its difficult to manually maintain and otherwise we're always going to leave some packages out inadvertently. FYI @bms63 as know you spotted updates on this before too like timber->logrx. think this low budget solution should work for all 😄

**Comment by bms63** [comment]
I did like the visual and have it in a presentation! :)  But totally understand that maintenance is a pain and everyone wasn't included.

**Comment by NNaikp** [comment]
Finally back to this! 🕐 

Generated some network visuals of contributors based on the visNetwork package and some of the data @epijim had already prepared for the current contributor visual.

Currently it looks like so:

![image](https://github.com/pharmaverse/pharmaverse/assets/85683724/eca746d2-279f-4a58-a494-29fa76e9130b)


However, I'm having trouble with embedding it on the page through iframe and I think hugo wants some sort of shortcode instead (which I don't have any experience with).

![image](https://github.com/pharmaverse/pharmaverse/assets/85683724/8996af28-f9d4-441e-bdfd-d38dd1423349)

Any feedback on the network is appreciated 😄

**Comment by rossfarrugia** [comment]
@epijim any advice on the above for Ari? 

@NNaikp i like the visual very much but also have the feeling it might be slightly overwhelming on a front page of a site. wondering if any way to make it more easily understandable at a glance? e.g. one option could be to have a way to allow the user to restrict the # of packages shown, such as filtering by package categories like "ADaM" for example, and then as default we just show one category which shows the connections between ~5 packages and user could select "All" for the full image. Just an idea though and feel free to ignore as I know the idea here was to show the full breadth of our dev community.

**Comment by bms63** [comment]
Sorry secret lurker that picture is amazing of us all with the open source packages.  Can we share that on slack.  It makes me so happy to see us all posted up there!

**Comment by rossfarrugia** [comment]
It'll be on the front page of the website soon once we find a way, but @NNaikp i'm fine if you wanted to share an early peak on slack?

**Comment by NNaikp** [comment]
@rossfarrugia It is not hard to modify, so I'll do a few different versions: filtered, in a hierarchical structure etc.
I think I might have found a fix for the integration, but I need to test it :)

@bms63 Hopefully it will be out soon 🚀 
It needs a little bit of tinkering still - like currently Eduardo is floating around as his own node without any arrows 😅

**Comment by rossfarrugia** [comment]
😆 @manciniedoardo might actually be proud of that, ha! He can be the Sun in our Solar System

**Comment by NNaikp** [comment]
Hierarchical can be seen [here](https://codepen.io/NNaikp/pen/abQvjVK) now.

LR Hierarchical with random levels:
![image](https://github.com/pharmaverse/pharmaverse/assets/85683724/528d1576-0577-46c0-8a66-439807f4554d)

I think this could be a less messy options. 
I'll see whether I can make the package image a bit larger.

**Comment by rossfarrugia** [comment]
Let's add it to our council agenda next week and see what everyone thinks 👍

**Comment by epijim** [comment]
still a bug in the HTML i think Error: Error building site: 

`"/home/runner/work/pharmaverse/pharmaverse/layouts/index.html:223:1": parse failed: template: index.html:223: template: multiple definition of template "main"`

`layouts/index.html` has 120ish lines, so things it's a script issue potentially

**Comment by NNaikp** [comment]
There were 2 definitions of the main page. I have fixed it here #246

**Comment by rossfarrugia** [comment]
@NNaikp the updates are looking good to me - very cool! i spotted a couple of incorrect package site links so i fixed these. some other comments (feel free to make updates directly in `develop` if easier to be able to check the test site):

- the hex wall doesn't match the package list [here](https://github.com/pharmaverse/pharmaverse/tree/develop/data/packages), e.g. ggsurvfit missing and synthetic.cdisc.data should be dropped (fine to only include admiral though and not all the package extensions)
- i think we should drop the section at the bottom of the page now for "**Website** Activity on the website and metadata is scraped automatically based on contributions to the codebase" - i don't feel like its so interesting anymore
- People section: is this accurate as i did a QC for example by checking admiralophtha and it only has Edoardo but when you look at the repo there are PRs from many different contributors
- In the issue above we had the numbers shown as well, e.g. Pharmaverse has X contributors - i'm not so worried about this for the # of packages as you can easily see that from the hex wall but for the people graphic it would be cool to easily be able to see the depth of our community via the total number

**Comment by NNaikp** [comment]
> @NNaikp the updates are looking good to me - very cool! i spotted a couple of incorrect package site links so i fixed these. some other comments (feel free to make updates directly in `develop` if easier to be able to check the test site):
> 
> * the hex wall doesn't match the package list [here](https://github.com/pharmaverse/pharmaverse/tree/develop/data/packages), e.g. ggsurvfit missing and synthetic.cdisc.data should be dropped (fine to only include admiral though and not all the package extensions)
> * i think we should drop the section at the bottom of the page now for "**Website** Activity on the website and metadata is scraped automatically based on contributions to the codebase" - i don't feel like its so interesting anymore
> * People section: is this accurate as i did a QC for example by checking admiralophtha and it only has Edoardo but when you look at the repo there are PRs from many different contributors
> * In the issue above we had the numbers shown as well, e.g. Pharmaverse has X contributors - i'm not so worried about this for the # of packages as you can easily see that from the hex wall but for the people graphic it would be cool to easily be able to see the depth of our community via the total number

1. The hexwall is controlled by the yaml files in the data/packages folder. The files should all have a ´hexwall: TRUE´ to be included in the wall. @mstackhouse mentioned that for new package requests we should provide a yaml shell we would like everybody to fill out. I have checked and added this input for the packages that were missing it 👍 

1. I have removed the "Website activity", but kept the code that generates this info in case we need it for something else.

1. I have re-used the old code to find contributors which is reading a .csv file hosted on the openPharma page. But when I compare the stats from the openPharma dashboard with OSS insights there is a big difference as you also highlight:

![image](https://github.com/pharmaverse/pharmaverse/assets/85683724/17e1b41e-7e22-49e7-b754-edc936c3c647)
![image](https://github.com/pharmaverse/pharmaverse/assets/85683724/33ee7d72-a78e-4572-8b37-c998f8a5400a)

I'll look into generating some code that is pulling directly from the main branches of all of the repos as we have the repo URLs in the yaml files.

1. I'll also look into adding this number - shouldn't be too hard.

**Comment by rossfarrugia** [comment]
@MathieuCayssol see the above around the openPharma site you created. The OSS insights stats don't seem to be correctly pulled - what do you think? Not urgent but might be something to look at when you get chance.

**Comment by NNaikp** [comment]
@rossfarrugia all of the above should be fixed now and I'm just waiting for the dev site to be deployed

**Comment by NNaikp** [comment]
It is there now. A bit slow though. I'll just look into whether we can optimise performance a bit.

**Comment by NNaikp** [comment]
> It is there now. A bit slow though. I'll just look into whether we can optimise performance a bit.

Yep, much better now - almost instant 😄

**Comment by rossfarrugia** [comment]
Looks amazing @NNaikp - i'll make a PR to main now. I swapped thevalidatoR (not really an R package) with datacutr which i spotted we had missed. that way we still keep the nice alignment you've achieved for now until more new packages come later.
