### ISSUE TITLE
Website homepage: Show E2E package pages clearer on the homepage under the main visual

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#213]
_@NNaikp suggestion: I think we should transpose the entire “End-to-End clinical reporting packages” to a tabset here and include it as its own section on the landing page. And then the usual topics._

I suggestion we update #212 first and see how it looks and then try to address this.

**Comment by rossfarrugia** [comment]
@NNaikp still think this one's necessary? now that we have the hex wall with the categories shown on each, personally i feel its covered and wouldn't suggest to change anymore for now.

**Comment by NNaikp** [comment]
@rossfarrugia I am fine with keeping the site as is now 👍
