### ISSUE TITLE
[BUG] tidyTLG doc link broken

### ISSUE THREAD

**Issue by NNaikp** [pharmaverse/pharmaverse#215]
**Describe the bug**
The tidyTLG package contains outdated info and links are not working

**To Reproduce**
1. Go to 'pharmaverse.org'
2. Click on End to end clinical reporting.
3. Click on TLGs
4. Scroll down to tidytlg
5. See text referring to OPEN SOURCE RELEASE EXPECTED ~MID 2022.

**Expected behavior**
As this package is a part of pharmaverse I would expect that it did not appear under "Upcoming packages for consideration".
That links work and link to a document page and to the github repository. Currently the doc link is recursive and links back to current page. The github link returns an error.

**Screenshots**
Github link:
![image](https://user-images.githubusercontent.com/85683724/227915738-73bd2173-3103-4000-bddf-3687b38be86b.png)

**Additional context**
NA

**Comment by nicholas-masel** [comment]
The [tlg index](https://github.com/pharmaverse/pharmaverse/blob/develop/content/e2eclinical/tlg/_index.en.md) is updated but the [dev site]( http://openpharma.s3-website.us-east-2.amazonaws.com/develop/e2eclinical/tlg/) isn't showing this update.  @epijim @rossfarrugia Any ideas off the top of your head why this isn't getting picked?
