### ISSUE TITLE
[BUG] ggplot2 info outdated and links broken

### ISSUE THREAD

**Issue by NNaikp** [pharmaverse/pharmaverse#216]
**Describe the bug**
ggplot2 doc link doesn't work

**To Reproduce**
1. Go to [https://pharmaverse.org/e2eclinical/tlg/](https://pharmaverse.org/e2eclinical/tlg/)
2. Scroll down to the bottom
3. Click on doc link for ggplot2.

**Expected behavior**
To be brought to the doc page for ggplot2

**Screenshots**
![image](https://user-images.githubusercontent.com/85683724/227916241-bfc0c699-2202-465c-b1e9-f35d3b2eb006.png)

**Additional context**
It seems like there is a duplication of the https element of the URL.

**Comment by rossfarrugia** [comment]
@nicholas-masel hope you're ok to fix this one when you fix #215
