### ISSUE TITLE
New packages need the usual badges shown

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#219]
eg see tidytlg and tidyCDISC:

![image](https://user-images.githubusercontent.com/82581364/229425528-c7c29e46-c29e-4712-9e7f-0cf67fca441a.png)

**Comment by nicholas-masel** [comment]
It looks like this is dependent on https://github.com/openpharma/openpharma.github.io.  Should we have a few of us join that along with James?

**Comment by rossfarrugia** [comment]
Yes could make sense for future! @MathieuCayssol helps maintain this, so could maybe take a look at this one for now. Let us know if that's ok Mathieu? I had a vague memory that this should have been automated in some way when new packages are added to pharmaverse but let me know if not.

**Comment by rossfarrugia** [comment]
thanks @MathieuCayssol! on the first bullet @mstackhouse is currently looking into a CRAN task view for pharmaverse so maybe that could help drive these in future.

**Comment by mstackhouse** [comment]
@rossfarrugia not yet, but I'll prioritize now that I'm back from vacation.

**Comment by mstackhouse** [comment]
@rossfarrugia see #269

**Comment by rossfarrugia** [comment]
Will close this issue as badges seem fine now
