### ISSUE TITLE
Help Wanted section in Contribute page

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#22]
Me and James have a future idea for the website to add a view that scrapes across our repos to pull issues that are open for contribution (tagged with “help wanted” or “good first issue”) out into a browsing list, so that any budding contributor could shop through the options (similar to and complimenting the Free Agent board idea Michael had, but putting the power in their hands to find opportunities to help). We’d add this to the [contribute](https://pharmaverse.org/contribute/) page later

**Comment by epijim** [comment]
We scrape this data daily currently - but don't use it in pharmaverse.org: https://openpharma.github.io/#data

Can flesh this out May 1st when we have someone on the Roche side focussed on OS discovery tools full time for 6 months.

**Comment by epijim** [comment]
This is what the data looks like today - but for all 225 packages tracked by openpharma, not filtered to just pharmaverse. I don't like this table as it's not that useful - we need some way to make the results better grouped into something like topics: 
![image](https://user-images.githubusercontent.com/2760096/161535259-23355c52-562e-4119-8a9a-4a18874c9af7.png)

**Comment by rossfarrugia** [comment]
@epijim for the pharmaverse site I'm imaging something like this but more targeted to entice them in. Something on https://pharmaverse.org/contribute/ic/ like:

**Help Wanted Board**

**Are you interested in contributing to open source?** _If so, the following shows a scrape of the Git repos for all pharmaverse recommended packages where issues are tagged with "help wanted" or "good first issue". If you'd like to contribute to any, then open up the respective issue and add a comment so that the author or development team could help arrange any required access/onboarding to help you get started._

then show a table only for the pharmaverse listed packages, and including and sorted by a category column (SDTM, ADaM, TLGs, eSub, etc matching from our site), then all the columns above except for comments and updated (i see them as superfluous), and for the description maybe truncate to include only the first XX characters instead of showing all.

it would be great if the table could be interactive to allow filtering, as likely most people will be interested in one specific area/category that they see themselves as an SME for.

**Comment by rossfarrugia** [comment]
Add http://openpharma.pharmaverse.org/ once available and make clear how packages get included here and issues - i.e.  "help wanted","good first issue","discussion" issue labels get scraped
