### ISSUE TITLE
[New package request] - datacutr

### ISSUE THREAD

**Issue by barnett11** [pharmaverse/pharmaverse#220]
- [x] I have first considered whether there is already an existing pharmaverse package that could solve this need, or if I could combine forces with an existing effort to add my features to their existing package.

- [x] I confirm I have read https://pharmaverse.org/contribute/lead/ and my package follows the Inclusion Criteria for pharmaverse.

**Name and description of package**
Supports the process of applying a cut to Standard Data Tabulation Model (SDTM), as part of the analysis of specific points in time of the data, normally as part of investigation into clinical trials. The functions support different approaches of cutting to the different domains of SDTM normally observed.

**Category of package**
SDTM utility

**Repository**
[A link to the publicly available source code.](https://github.com/pharmaverse/datacutr)

**Package Maintainer**
timothy.barnett@roche.com

**Who is involved in developing/maintaining this package?**
Tim Barnett, Alana Harris (alana.harris@roche.com) and Nathan Rees (nathan.rees@roche.com) - Primarily out of Roche with Ross Farrugia as sponsor

**Considerations for pharmaverse inclusion**
https://pharmaverse.github.io/datacutr/main/

**Overall fit in pharmaverse**
It has universal application for handling SDTM datacut approach

**Comment by rossfarrugia** [comment]
Thanks Tim! The Data Eng WG will review this and get back to you.

**Comment by elimillera** [comment]
Thanks @barnett11. We had the following question about functionality [here](https://github.com/pharmaverse/datacutr/issues/171), but otherwise looked to be a great fit for the pharmaverse!
