### ISSUE TITLE
Deprecated functions need to be removed from example section 

### ISSUE THREAD

**Issue by sadchla-codes** [pharmaverse/pharmaverse#225]
Some of the admiral functions used in the examples from (http://examples.pharmaverse.org/data/adsl )are being deprecated in version 0.10.0 so the section below need to be updated
![image](https://user-images.githubusercontent.com/112789549/234308696-205eae19-f018-4f0e-8db0-b3e0a7bc6595.png)

**Comment by rossfarrugia** [comment]
Thanks Sadchla! Moved issue to the examples repo for this: https://github.com/pharmaverse/end_to_end_examples/issues/26. There's quite a few updates we need to make there, so added it to my list.
