### ISSUE TITLE
[New package request] - DataWG - synthetic.cdisc.data

### ISSUE THREAD

**Issue by elimillera** [pharmaverse/pharmaverse#235]
**Name and description of package**
synthetic.cdisc.data
Package used to create CDISC-like synthetic data

**Category of package**
Utility

**Repository**
[synthetic.cdisc.data](https://github.com/Roche/synthetic.cdisc.data)

**Package Maintainer**
@gmbecker

**Who is involved in developing/maintaining this package?**
Roche

Reviewers:
@elimillera @MichaelRimler @AxelMuehlig

**Comment by elimillera** [comment]
Description of Automated Tests/Checks:
An automated pipeline is present, however it only tests on ubuntu on one version of R. It is recommended that multiple OS and versions of R are tested.
No tests are present for that package.

Description of Package Documentation:
No README, vignettes, or function documentation is present. Function documentation doesn't detail use or how it works 
As it relies on a non CRAN package (respectables), installation instructions should be added to the README to note how to install that package.


Description of Functionality and Package Structure:
Functionality cannot be confirmed as there are no examples or getting starting guide.

Overall review of package and fit in pharmaverse:
Likely does close a gap to create synthetic data when the data in safetyData is insufficient. however, package is missing tests and documentation.

**Comment by AxelMuehlig** [comment]
Similar questions like Eli about documentation, examples etc.

One additional question: Aren't there already some publicly available synthetic SDTM data?

**Comment by gmbecker** [comment]
Data generated with this package are publicly available.

A fairly old but nearly full ADaM set is bundled with the CRAN `formatters` package (which underlies both `rtables` and `rlistings`), in the form of `ex_adsl`, `ex_adae`, etc. 

Furthermore, there is the scda package (https://github.com/insightsengineering/scda), which stands for synthetic cdisc data archive. Associated with that are numerous snapshots of synthetic ADaM datasets (e.g., https://github.com/insightsengineering/scda.2022), which are publicly available. 

These datasets are what is used in the tlg-catalog (see, e.g., https://insightsengineering.github.io/tlg-catalog/tables/adverse-events/aet01.html).

**Comment by gmbecker** [comment]
Actually I should be a bit careful here, I'm not certain if the data in scda is generated via `synthetic.cdisc.data` or `random.cdisc.data` which are related but different packages. @shajoezhu would know.

**Comment by shajoezhu** [comment]
hi @gmbecker , thanks for the tag. scda is just a loader, current data is stored in scda.2022, which are cached data from running random.cdisc.data. We are still maintaining and updating
