### ISSUE TITLE
DataWG: {Package Review}: admiral

### ISSUE THREAD

**Issue by elimillera** [pharmaverse/pharmaverse#238]
**Name and description of package**
admiral

**Category of package**
ADaM

**Repository**
https://github.com/pharmaverse/admiral

**Package Maintainer**
Ben Straub @bms63 

**Considerations for pharmaverse inclusion**
Describe license type, automated tests/checks, and package documentation.

**Overall fit in pharmaverse**
Why you believe this should belong in the pharmaverse? Please call out any novel or duplicative functionality relative to the existing pharmaverse packages.

Reviewer:
@elimillera @MichaelRimler @AxelMuehlig

**Comment by bms63** [comment]
I believe going forward we won't be introducing issues where version conflicts arise between `admiraldev` and `admiral`.  

Just to put in some context:  The split out of the functions (developers versus user focused functions) was to make it easier for new developers to understand how to use them and reduce clutter in the admiral codebase.  If we put them back into admiral they will need to hidden from users, which reduces their visibility to new developers. In moving all the developer-facing functions, we found a lot of them overlapped or weren't even in use which greatly reduced the number functions.

However, I'm open to the idea of removing `admiraldev` to bring us to more simplistic way of working.  We could make `admiraldev` like `admiralci` where the package is just a website with our dev docs.   Maybe there is a way for us to render the documentation for our dev functions on our dev site and keeping them hidden from users within `admiral`.  

 @pharmaverse/admiral any thoughts?

**Comment by rossfarrugia** [comment]
I feel your first few sentences Ben justify our decision and therefore fine to keep as is. Given we're striving for these to reach a greater level of maturity soon then it works for me to keep as is. Also its not only all the admiral family of packages that changing this would impact, but look at say {datacutr} which uses {admiraldev} utility functions and they appreciate not having the heavier dependency of {admiral} here

**Comment by rossfarrugia** [comment]
Closing this issue now as Data WG were happy with keeping package
