### ISSUE TITLE
Idea: hex logo guidance for package devs

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#239]
**Describe your idea**
@statasaurus suggested we should give guidance to pkg devs on hex logo requirements for our website, e.g. ensuring no background whitespace. we could add to https://pharmaverse.org/contribute/lead/

@NNaikp do you have any guidance you could suggest here from your work on the homepage hex wall?

**Comment by NNaikp** [comment]
From building the initial hexwall view then what scales absolutely best is high-resolution PNGs with no edge space/margins on the vertical edges of the hex, just like xportr hex: ![this](https://pharmaverse.github.io/logrx/reference/figures/logo.png).

Something with edges like below will unfortunately scale worse. It is hard to see here, but if you visit the links [xportr](https://pharmaverse.github.io/logrx/reference/figures/logo.png) and [visR](https://openpharma.github.io/visR/reference/figures/logo.png) you can see a difference in the vertical edging.
![this](https://openpharma.github.io/visR/reference/figures/logo.png)
