### ISSUE TITLE
Idea: Separate packages for users and developers

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#240]
**Describe your idea**
Idea from a Tech/Templates WG discussion: 
Some packages like those around validation or synthetic data might be better moved to a separate website section more for Developers. So that our e2e Clinical Reporting list of packages remains focused on users.
Then we could also consider adding extra pieces we have like the admiral test data package and the admiral CI checks.
We could link the new website section via this page https://pharmaverse.org/contribute/lead/

@pharmaverse/core-team any thoughts/objections??

**Comment by MichaelRimler** [comment]
@rossfarrugia: I like this idea. Of course, users could still pick up those packages and use them for themselves, but that would not be the 'recommended' use by pharmaverse. Rather, pharmaverse would position them to be used by developers. It also may create a channel of developing pan-pharmaverse utility packages that developers find useful.

**Comment by rossfarrugia** [comment]
Created a placeholder page in `develop` branch for now but need to add CI/CD and test data recommendations.
