### ISSUE TITLE
[BUG] navbar sizing

### ISSUE THREAD

**Issue by epijim** [pharmaverse/pharmaverse#247]
**Describe the bug**
PHUSE hex is mis-sized, appearing large and increasing the height of the navbar.

![image](https://github.com/pharmaverse/pharmaverse/assets/2760096/ad433e9c-aa34-4c3d-b48d-f77ca008b8d7)

@rossfarrugia - is it intended to have phuse rather than pharmaverse hex in this location as well? It seems a bit weird as that's the spot the project/package hex always goes.

**Comment by rossfarrugia** [comment]
@epijim i'll try and make it bit smaller again but wanted to be sure the "supported" is readable. i think as we have the big pharmaverse logo below anyway i thought nice place to put the phuse acknowledgement
