### ISSUE TITLE
Add Biomarker Analysis Catalog link

### ISSUE THREAD

**Issue by danielinteractive** [pharmaverse/pharmaverse#253]
I think it would make sense to also add the Biomarker Analysis Catalog: https://insightsengineering.github.io/biomarker-catalog/

(As a bullet below TLG catalog)

It fits well with clinical reporting as we primarily use NEST packages in BAC and biomarker analyses are also part of clinical reporting.

**Comment by rossfarrugia** [comment]
No problem for me. @mstackhouse you ok with this?

**Comment by rossfarrugia** [comment]
@mstackhouse i'm making a round of site updates so going to add this - just shout if any concern
