### ISSUE TITLE
Reset button in the spider plot 

### ISSUE THREAD

**Issue by statasaurus** [pharmaverse/pharmaverse#256]
**Describe your idea**
I would like a button to reset the zooming of the spider plot. Sometimes as I am scrolling through I zoom the graph out of the window and then I have to refresh the page in order to get the map back.

**Comment by rossfarrugia** [comment]
@NNaikp any thoughts?

**Comment by NNaikp** [comment]
The plot is rendered on a page update. What we can do instead is to remove the mouse scroll and add navigation buttons instead so you don't get caught by the plot?

**Comment by rossfarrugia** [comment]
I guess people could still get lost with nav buttons and end up only in white space so i leave it to you to make the call here @NNaikp. I also see it as a minor thing so also would be happy if you chose to close the issue with no update.

**Comment by rossfarrugia** [comment]
lets close with no update - seems to be working fine as it is and we don't have many volunteers helping with the website currently
