### ISSUE TITLE
[New package request]: pharmaversesdtm

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/pharmaverse#259]
- [x] I have first considered whether there is already an existing pharmaverse package that could solve this need, or if I could combine forces with an existing effort to add my features to their existing package.

- [x] I confirm I have read https://pharmaverse.org/contribute/lead/ and my package follows the Inclusion Criteria for pharmaverse.

**Name and description of package**
pharmaversesdtm: SDTM test data to be used across the pharmaverse. supersedes admiral.test.

**Category of package**
SDTM

**Repository**
[repo](https://github.com/pharmaverse/pharmaversesdtm)

**Package Maintainer**
@manciniedoardo 

**Who is involved in developing/maintaining this package?**
@manciniedoardo @kaz462 

**Considerations for pharmaverse inclusion**
Same license as admiral package? Apache 2.0

**Overall fit in pharmaverse**
As a successor and improvement of admiral.test, this package naturally belongs in the pharmaverse.

**Comment by rossfarrugia** [comment]
@manciniedoardo fine to include this as we already have it mentioned on this page anyway: https://pharmaverse.org/e2eclinical/developers/. Looking at the way the page reads for now, I'll wait for {pharmaverseadam} to come in the coming months and then will make the update to this page all in one go to list these out like the other packages with their hex, site links and description etc.
