### ISSUE TITLE
[New package request] - `rhino`

### ISSUE THREAD

**Issue by jakubnowicki** [pharmaverse/pharmaverse#260]
- [x] I have initially assessed whether there is an existing Pharmaverse package that could fulfill this requirement, or if it would be feasible to collaborate with an ongoing project to integrate my features into their existing package.

- [x] I affirm that I have reviewed [Pharmaverse Contribution Guidelines](https://pharmaverse.org/contribute/lead/) and my package aligns with the Pharmaverse Inclusion Criteria.

## Name and Description of the Package
**Package Name:** Rhino

Rhino is an R package crafted to facilitate the swift development of high-quality, enterprise-level Shiny applications. It empowers creators to build Shiny apps that adhere to the best software engineering practices, featuring modular, thoroughly tested code, and an aesthetically pleasing UI.

Rhino operates as an opinionated framework, emphasizing best practices and advanced development tools. It encompasses three primary domains:
1. **Clear Code:** Scalable app architecture, modularization leveraging `box` and Shiny modules.
2. **Quality:** Incorporates unit tests, E2E tests via Cypress, along with comprehensive logging, monitoring, and linting capabilities.
3. **Automation:** Streamlines project initiation, CI through GitHub Actions, dependency management via `renv`, configuration management utilizing `config`, and facilitates Sass and JavaScript bundling with ES6 support through Node.js.

## Package Category
TLGs, as it facilitates the creation of interactive Shiny applications that function as a container for TLGs.

## Repository
You can find the publicly available source code [here](https://github.com/Appsilon/rhino/).

## Package Maintainer
**Maintainer (on a break until December):** Kamil Żyła (@kamilzyla)  
**Interim Maintainer:** Jakub Nowicki (@jakubnowicki)

## Development and Maintenance Team
**Copyright Holder (Company):** [Appsilon](https://appsilon.com)  
**Contributors:**
- Recle Vibal (@vibalre)
- Tymoteusz Makowski (@TymekDev)
- Marek Rogala (@marekrogala)
- Eduardo Almeida (@Eduardodudu)
- Leszek Siemiński (@Leszek-Sieminski)

#### License: LGPL-3
**Reasons for Choosing LGPL-3:**
- It encourages the open-source nature of derivative works.
- For instance, if someone enhances Rhino and releases a new version named Elephant, we aspire for Elephant to remain open-source.
- LGPL-3 distinctly clarifies that a Shiny app utilizing the Rhino package is not a derivative work, allowing it to possess any desired license.
- Contrarily, if the package was under AGPL, the Shiny app would be deemed a derivative work, necessitating it to be open-sourced.

#### Testing
The package includes unit tests but recognizes that these are not sufficient to fully assess the complex functionalities of the application, especially given its role in scaffolding Shiny applications and offering development tools. To complement this, it also encompasses a wide range of end-to-end tests, which are vital in ensuring the smooth operation of integrated functionalities, such as JavaScript code bundling. This multi-faceted approach to testing guarantees a higher degree of reliability and efficiency. Furthermore, the continuous integration (CI) system rigorously tests the package across various operating systems and R versions, solidifying its robustness.

#### Documentation
The package furnishes comprehensive vignettes, accessible on the [documentation page](https://appsilon.github.io/rhino/).

## Alignment with Pharmaverse
Rhino emerges as a vital addition to the Pharmaverse package repository, a hub primarily centered on detailed clinical trial data reporting. While many existing packages focus on safeguarding the accuracy and reliability of data, the introduction of Rhino fills a significant gap by significantly enhancing the reliability and quality of Shiny applications in various crucial aspects.

Rhino fosters the development of Shiny applications that not only adhere to clear coding standards but also uphold stringent quality assurance practices, including automation. This commitment to quality ensures the creation of highly reliable applications, enhancing the trust and dependability in the results they present. Moreover, it amplifies the reproducibility and clarity of the results showcased by these applications, establishing a new benchmark in creating user-friendly and trustworthy applications.

**Comment by mstackhouse** [comment]
I'm supportive of this - @statasaurus, @telepath37  - any disagreement with admitting rhino?

**Comment by rossfarrugia** [comment]
I spoke with the NEST team offline on this and they were in agreement as rhino is already well established, so we can take that as a yes from Vincent (as he's away at a conference). If I don't hear any disagreement next week then I'll add this package then as need to make some other site updates same time.

**Comment by statasaurus** [comment]
I'm supportive
