### ISSUE TITLE
[New package request] - {datasetjson}

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#261]
- [x] I have first considered whether there is already an existing pharmaverse package that could solve this need, or if I could combine forces with an existing effort to add my features to their existing package.

- [x] I confirm I have read https://pharmaverse.org/contribute/lead/ and my package follows the Inclusion Criteria for pharmaverse.

**Name and description of package**
@mstackhouse and @nicholas-masel  - R package to create datasetjson (see https://atorus-research.github.io/datasetjson/index.html)

**Category of package**
Utility

**Repository**
https://github.com/atorus-research/datasetjson - but team would like to move this to pharmaverse org.

**Package Maintainer**
Mike

**Who is involved in developing/maintaining this package?**
Atorus license owner, 2 contributors as above (Atorus/J&J)

**Considerations for pharmaverse inclusion**
Sure of a reasonable standard given Mike wrote most of the inclusion criteria ;)

**Overall fit in pharmaverse**
At CSS next week one of the big things going on is a workshop around Dataset JSON (among a lot of other Dataset JSON related things - it's a big topic this year). Sam Hume had connected with Mike a little while back about getting a truly functional R based solution for the workshop, because the initial hackathon didn't yield an actual package.

**Comment by rossfarrugia** [comment]
@elimillera @MichaelRimler @AxelMuehlig i think this one would be good for the DataWG to review. let's discuss at our call next week and kick off the review for Mike and Nick.

**Comment by rossfarrugia** [comment]
just to add from my side that i have no concerns with adding this to pharmaverse org and our site.
@mstackhouse @nicholas-masel minor comment but a hex logo would be nice to get added here when you get chance.

**Comment by mstackhouse** [comment]
We've got one! It's just not merged to main quite yet. https://github.com/atorus-research/datasetjson/blob/github_issue_3_16/man/figures/logo.svg

**Comment by nicholas-masel** [comment]
I'll get the pr reviewed today

**Comment by AxelMuehlig** [comment]
Hi,
Conceptually, I think it's a good idea to include it in Pharmaverse. A few questions/comments:

- I saw in the readme that we don't recommend it for production use until the format has become more clear from CDISC. We should make it clear on the Pharmaverse page, maybe label as experimental or similar.
- I assume the content from the atorus page will be used as documentation? It does contain a note about not using it for production so would also address my first comment.

No additional comments.

**Comment by rossfarrugia** [comment]
agree @AxelMuehlig

**Comment by MichaelRimler** [comment]
I have no additional comments - but agree with comments from @AxelMuehlig

**Comment by rossfarrugia** [comment]
@mstackhouse you have approval from the Data WG. do you want to move this repo over to pharmaverse GH org already now? you should have access to do this. once its there i can make the pharmaverse site updates to link to this and will explain its still an experimental package by nature as per above comments.

**Comment by mstackhouse** [comment]
@rossfarrugia I just did a CRAN release, so I'll migrate the repository during our next CRAN release so that all the URLs can update at once.

**Comment by rossfarrugia** [comment]
sure @mstackhouse - i'll add it to pharmaverse website for now with the current links and just message me later when the repo moves org and i can update them then

**Comment by rossfarrugia** [comment]
@mstackhouse it's there now and i labeled it as experimental in the description text. feel free to put a message out to pharmaverse slack on this to raise awareness.
