### ISSUE TITLE
[New package request] pharmaverseadam

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/pharmaverse#262]
- [x] I have first considered whether there is already an existing pharmaverse package that could solve this need, or if I could combine forces with an existing effort to add my features to their existing package.

- [x] I confirm I have read https://pharmaverse.org/contribute/lead/ and my package follows the Inclusion Criteria for pharmaverse.

**Name and description of package**
pharmaverseadam: A set of Analysis Data Model (ADaM) datasets constructed using the Study Data Tabulation Model (SDTM) datasets contained in the 'pharmaversesdtm' package and the template scripts from the 'admiral' family of packages. 

**Category of package**
ADaM test data

**Repository**
[repo](https://github.com/pharmaverse/pharmaverseadam)

**Package Maintainer**
@manciniedoardo 

**Who is involved in developing/maintaining this package?**
@manciniedoardo @kaz462 

**Considerations for pharmaverse inclusion**
Same license as admiral package? Apache 2.0

**Overall fit in pharmaverse**
This package aims to be the on-stop-shop for ADaM test data in the pharmaverse. NEST is as already planning to use it for test data.

**Comment by rossfarrugia** [comment]
Will add this, as per comment at https://github.com/pharmaverse/pharmaverse/issues/259
