### ISSUE TITLE
[Idea] - CRAN Task View

### ISSUE THREAD

**Issue by mstackhouse** [pharmaverse/pharmaverse#269]
**Describe your idea**

Creation of a CRAN Task View for pharmaverse. 

_Note: CRAN task views must point to packages on CRAN itself. As such, some packages listed on the pharmaverse site won't be able to be included in the task view._

**Comment by mstackhouse** [comment]
First draft is available here: https://github.com/pharmaverse/pharmaverse_task-view

**Comment by mstackhouse** [comment]
@rossfarrugia I've drafted the initial task view on the main branch of the repo above. I need some volunteers for maintainers - this is from the CTV Proposal guidelines:

> The proposal should be made by the person willing to act as the principal maintainer for the task view. Furthermore, task views should have teams of additional 1-5 co-maintainers to share the workload and reflect different perspectives. Ideally the co-maintainers should be a diverse group in terms of gender, origin, scientific field, etc. Possible candidates can be listed in the proposal.

Full proposal list here: https://github.com/cran-task-views/ctv/blob/main/Proposal.md

**Comment by rossfarrugia** [comment]
@mstackhouse thanks for this! Happy to be one of the co-maintainers. How about you opening it up on pharmaverse Slack for other volunteers? might be a nice opportunity for some from our community. then once the CTV is live we can add a link to it and a mention on our website.

**Comment by rossfarrugia** [comment]
@mstackhouse was the CTV proposal made? if it launches i'll add something to the package request template and readme files here to remind that any new CRAN packages added to our site should also get added to the CTV.

**Comment by mstackhouse** [comment]
@rossfarrugia I have not  yet drafted. I can work on that in the coming weeks unless you or @AARON-CLARK wants to write it.

**Comment by rossfarrugia** [comment]
@mstackhouse thats fine, good to wrap up before xmas if we can. happy if you could do it and if we get accepted then i'll make updates to our site etc for it.

**Comment by mstackhouse** [comment]
Note sent to ClinicalTrials maintainers here: https://github.com/cran-task-views/ctv/issues/59

**Comment by rossfarrugia** [comment]
@mstackhouse where did we get to in the end with this? was it a no go from the CTV folks?

**Comment by mstackhouse** [comment]
IIn my opinion it started deviating from our original intent. The resulting CTV would probably end up not really being "pharmaverse" so maybe we look back at this in another year or so and see if it makes more sense then with the volume of packages and scope.

**Comment by mstackhouse** [comment]
I'm going to close this for now.
