### ISSUE TITLE
{visR} lifecycle and pharmaverse future 

### ISSUE THREAD

**Issue by bailliem** [pharmaverse/pharmaverse#273]
Hi @rossfarrugia , 

with the v0.4 release of [{visR}](https://github.com/openpharma/visR/releases/tag/v0.4), we are now recommending users adopt functions from [{ggsurvfit}](https://github.com/pharmaverse/ggsurvfit). As a result, we have [deprecated](https://github.com/openpharma/visR/releases/tag/v0.4) those functions in {visR} as of v0.4. 

The developers of visR still have many unanswered questions about where we want to take it, and importantly if we'll take it anywhere. Given its uncertain future, we thought it would be prudent to **remove** it from the pharmaverse collection for now if this is possible.  

FYI [@cschaerfe](https://github.com/cschaerfe), [@ddsjoberg](https://github.com/ddsjoberg),

**Comment by rossfarrugia** [comment]
No problem, will try and update this later this week.
