### ISSUE TITLE
[New package request] chevron and falcon

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#279]
@mstackhouse @statasaurus - any objection to me updating the TLG page to move the following 2 up to the main section of the page now as both are now open sourced?

![image](https://github.com/pharmaverse/pharmaverse/assets/82581364/9acc9aa6-4cd2-4aeb-8a77-822493615d74)

@telepath37 i'm sure is fine with this as he's part of both teams.

chevron is also now on CRAN, but i saw a falcon package already exists on CRAN so maybe @pawelru could share the latest thinking for that one.

**Comment by pawelru** [comment]
Re: "falcon" package name. This had been raised for awareness at the POs meeting some time ago but no conclusion about the new name as of yet. But we all agreed that that needs to happen - it's just a matter of finding a new name.

**Comment by mstackhouse** [comment]
I have no issue with this.

**Comment by statasaurus** [comment]
I think before we put it on the website it should have the new name. I think will be confusing for people to have to deal with the name change. I think we have in our documentation we need to wait until it is on CRAN and I think we should try not to make too many exceptions to that rule

**Comment by statasaurus** [comment]
I am fine with chevron being added

**Comment by rossfarrugia** [comment]
Makes sense! It's already on the website at the bottom of the page in the "consideration" section so will add a note about the upcoming name change and leave falcon there for now til its newly named and on CRAN, and will move chevron up for now. Will pick up the website updates later in the week, and @pawelru could notify us later once re-branded falcon is on CRAN.
