### ISSUE TITLE
[Idea] - optimise home page loading

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#281]
**Describe your idea**
@NNaikp any way we could speed up the loading of the homepage given the nice dynamic visualizations? it hangs for me usually for 10 seconds or so before i can scroll down. i wonder if any way to optimise? just thinking some newcomers may get put off by this and close the tab instead of waiting.

**Comment by NNaikp** [comment]
Which browser are you using?
It loads instantly for me 🤔

**Comment by rossfarrugia** [comment]
Chrome - wonder if its only on my side then. @mstackhouse @MichaelRimler how does the pharmaverse.org site load for you guys?

**Comment by MichaelRimler** [comment]
No issues for me on chrome or edge. (or safari on mobile). @rossfarrugia  - perhaps check on your personal machines and not via any organizational specific 'scripts' that might be working in the background...see if you get the same slowness?

**Comment by mstackhouse** [comment]
Same - I'm not having any issues.

**Comment by rossfarrugia** [comment]
i tried in incognito mode and worked great - probably just need to clear cache/cookies in my browser. thanks for checking all, will close this.
