### ISSUE TITLE
[New package request] Adding {cards}

### ISSUE THREAD

**Issue by ddsjoberg** [pharmaverse/pharmaverse#286]
- [x] I have first considered whether there is already an existing pharmaverse package that could solve this need, or if I could combine forces with an existing effort to add my features to their existing package.

- [x] I confirm I have read https://pharmaverse.org/contribute/lead/ and my package follows the Inclusion Criteria for pharmaverse.

**Name and description of package**
{cards}: The package is used to construct CDISC-compliant Analysis Results Data Set (ARDs) objects. These objects are used and re-used to construct summary tables, visualizations, and written reports. Statistical summaries are calculated and stored in a general format, and tables and figures can be created from these calculated statistics. The ARDs can be re-used to construct different summaries of the same data, for QC purposes, and for medical writers summarizing results. The package also exports utilities for working with these objects and creating new ARD objects. 

These ARD objects live in the space between ADaM data sets and TLGs. The ARDs created with {cards} can be used to construct tables with {tfrmt} with support for {gtsummary} coming soon.

**Category of package**
TLGs

**Repository**
https://github.com/insightsengineering/cards

**Package Maintainer**
@ddsjoberg 

**Who is involved in developing/maintaining this package?**
Becca Krouse (GSK), Roche, GSK

**Considerations for pharmaverse inclusion**
Describe license type, automated tests/checks, and package documentation.

The package is licensed under Apache License 2.0, includes a CI/CD pipeline for integration tests and documentation with > 99% code coverage. The package is well-documented with a pkgdown website, informative help files, and articles illustrating use cases. 

**Overall fit in pharmaverse**
The {cards} package is a good fit for the pharmaverse as it supports an emerging standard sponsored by CDISC that is not yet available in other packages.

**Comment by rossfarrugia** [comment]
@mstackhouse @statasaurus @telepath37 - can you take a look and let me know if ok to add this package to pharmaverse?

**Comment by mstackhouse** [comment]
This is a no-brainer for me! I approve.

**Comment by statasaurus** [comment]
I approve
