### ISSUE TITLE
[New package request] {tfrmtbuilder}

### ISSUE THREAD

**Issue by bzkrouse** [pharmaverse/pharmaverse#287]
- [x] I have first considered whether there is already an existing pharmaverse package that could solve this need, or if I could combine forces with an existing effort to add my features to their existing package.

- [x] I confirm I have read https://pharmaverse.org/contribute/lead/ and my package follows the Inclusion Criteria for pharmaverse.

**Name and description of package**
{tfrmtbuilder} contains a Shiny app interface for the {tfrmt} package (existing Pharmaverse package for table creation). {tfrmtbuilder} extends the functionality of {tfrmt} to a wider user base by easing the learning curve for new users and facilitating customizations for non-programmers. Users can quickly and easily create new tables or modify existing ones, and then save the resulting display and metadata.

**Category of package**
TLGs

**Repository**
https://github.com/GSK-Biostatistics/tfrmtbuilder

**Package Maintainer**
@bzkrouse

**Who is involved in developing/maintaining this package?**
GSK

**Considerations for pharmaverse inclusion**
Describe license type, automated tests/checks, and package documentation.

The package is licensed under Apache License 2.0 and utilizes automated checks via GitHub Actions. It also includes a growing suite of interactive shinytest2-based tests. A pkgdown site is available containing a high level description of the app and possible workflows. 

**Overall fit in pharmaverse**
{tfrmtbuilder} is a good fit for the pharmaverse because it increases the accessibility of an existing pharmaverse package, {tfrmt}. As they have been co-developed by GSK they will remain harmonious, with {tfrmt} serving as the engine for the app.

**Comment by rossfarrugia** [comment]
@mstackhouse @statasaurus @telepath37 - can you take a look and let me know if ok to add this package to pharmaverse?

**Comment by rossfarrugia** [comment]
@NNaikp hold off merging https://github.com/pharmaverse/pharmaverse/pull/288 if you approve, as i might squeeze this one in too next week.
