### ISSUE TITLE
Package icons spilling into next section

### ISSUE THREAD

**Issue by bms63** [pharmaverse/pharmaverse#289]
Using Edge Browser - the package hexes are spilling out of the frame

![image](https://github.com/pharmaverse/pharmaverse/assets/10111024/0130b3cc-ae59-4386-b0de-e2b8d57630a4)

**Comment by NNaikp** [comment]
Oh no, we're growing faster than our divs!
I'll take a look at it this week 😄

**Comment by NNaikp** [comment]
Fix just released on main page! 😄 
[pharmaverse](https://pharmaverse.org/)

**Comment by NNaikp** [comment]
Closing

**Comment by bms63** [comment]
Looks nice!!
