### ISSUE TITLE
[New package request] rlistings

### ISSUE THREAD

**Issue by shajoezhu** [pharmaverse/pharmaverse#291]
- [x] I have first considered whether there is already an existing pharmaverse package that could solve this need, or if I could combine forces with an existing effort to add my features to their existing package.

- [x] I confirm I have read https://pharmaverse.org/contribute/lead/ and my package follows the Inclusion Criteria for pharmaverse.

**Name and description of package**

The `rlistings` R package is a package that was designed to create and display listings with R. The focus of this package is to provide functionality for value formatting and ASCII rendering infrastructure for tables and listings. Many of the functions contained in rlistings depend on the [formatters](https://insightsengineering.github.io/formatters/) package, which provides a framework for ASCII rendering and is available on CRAN.

**Category of package**
TLGs

**Repository**
https://github.com/insightsengineering/rlistings

**Package Maintainer**
@shajoezhu

**Who is involved in developing/maintaining this package?**
License owners, contributors, and which companies/industry groups are involved?
Roche NEST SME team, 

**Considerations for pharmaverse inclusion**
Describe license type, automated tests/checks, and package documentation.

The package is licensed under Apache License 2.0, includes a CI/CD pipeline for integration tests and documentation with > 87% code coverage. The package is well-documented with a pkgdown website, informative help files, and articles illustrating use cases.

**Overall fit in pharmaverse**
The package is a good fit for pharmaverse as it is the package to create listings. also one of the backend packages for the chevron package.

**Comment by rossfarrugia** [comment]
@mstackhouse @statasaurus - can you take a look and let me know if ok to add this package to pharmaverse?

@telepath37 is part of this team so i'm sure agrees.

**Comment by rossfarrugia** [comment]
@mstackhouse @statasaurus reminder to check above please. if no word by end of the week then i'll take the call to add this package given we already have rtables from same team in pharmaverse and listings are a gap in our current offerings.

**Comment by rossfarrugia** [comment]
@shajoezhu now added to the site. feel free to add the badge to your github repo: https://pharmaverse.org/contribute/badges/

**Comment by shajoezhu** [comment]
Thanks so much Ross!
