### ISSUE TITLE
Setup hex stickers on main page

### ISSUE THREAD

**Issue by epijim** [pharmaverse/pharmaverse#3]
![image](https://user-images.githubusercontent.com/2760096/129537260-99a7e864-edd5-4e7d-bae8-fb4b671ebe71.png)

**Comment by epijim** [comment]
Added code so these data elements 
![image](https://user-images.githubusercontent.com/2760096/129804012-575bf1de-b526-48e9-b7c8-44445a4f32af.png)

which currently look like this 

![image](https://user-images.githubusercontent.com/2760096/129804076-bccfe8ca-c979-4f6a-938b-ed6eef34f33a.png)

generate the following

![image](https://user-images.githubusercontent.com/2760096/129804116-f2668d36-21a2-4bea-bf3f-d590d21aade8.png)

**Comment by rossfarrugia** [comment]
@epijim can we update this list to include all the current open source packages from https://pharmaverse.org/e2eclinical/, so should be:
tplyr, pharmartf, rtables, xportr, pkglite, metacore, timber, riskmetric, valtools

then we can update this as more become open source.

i didn't have synthetic.cdisc.data on the package list - is this open source? how does it compare to the CDISC pilot offerings? i know admiral used dummy SDTM data from this: https://bitbucket.cdisc.org/projects/CED/repos/sdtm-adam-pilot-project/browse/updated-pilot-submission-package/900172/m5/datasets/cdiscpilot01

**Comment by epijim** [comment]
Right now it's hardcoded to only show 6 (as the location of each 6 is manually defined), but it pulls what to plug into the 6 spots from the `yaml` data dynamically. Need to switch it over to a 'dynamic' one. e.g. 

https://css-tricks.com/building-a-hexagonal-grid-using-css-grid/

Will take a look - but CSS isn't my strong suit so might take a few evenings of tinkering.

**Comment by epijim** [comment]
For CDISC's data - my understanding was, why would you need it pre-compiled. And then diverse data is needed for unit testing, so flexible functions to define the data on the fly is preferred. So I think it's more about quality of unit testing. Will ask the team to confirm this though.

**Comment by rossfarrugia** [comment]
thanks James! would be cool if we can get it to show a grid of all the hex logos, as it always paints a great picture when we show something like that in slides and it helps people gauge the depth of pharmaverse, and also see how it grows over time.

np on the CDISC data. i guess useful for integration testing or unit testing something quite big that's not been split into modular functions, as in that case i'd prefer to feed in my own test cases where i could cover the main scenarios. i added the package to the list anyway as if we deemed it was needed at Roche then sure some other companies will have same need too.

**Comment by rossfarrugia** [comment]
p.s. @epijim i wasn't thinking of load times when i made the above request - it's a nice to have if it would mean adding loads of hexes would slow down the page load speed. i like the selection you have on the front page now as shows a good variety (assuming NEST open sources soon - might be a case to include Tplyr in there instead as an already open sourced example)

**Comment by mstackhouse** [comment]
@rossfarrugia  and @epijim - I don't know that this warrant _another_ issue, but those main page hex stickers highlight when you hover over them, but there's no link applied. Could we link them directly into the e2e page? That would make intuitive sense. 

I don't think they should link directly to the package GitHub pages or websites, because I think it would then make it easy for people to miss the e2e page in the first place, because those stickers are so front and center.

**Comment by rossfarrugia** [comment]
thanks @mstackhouse - nice idea!
i also copy in your comment from email here which i agree with as it definitely wasn't meant to imply "core" packages:

 The landing page at https://pharmaverse.org/ has 6 packages in the list. This gives me a tidyverse.org vibe – but the thing here is that at tidyverse.org, those are the “core” tidyverse packages. We haven’t discussed, and I don’t that this is trying to imply, a core set of packages. That said, when I looked at it I selfishly thought “well what about Tpylr”? All I’d really want to see here is just a “and more!” or something like that, to the right of the package hexes that just has it really clear and up front that pharmaverse is larger than those 6.

**Comment by rossfarrugia** [comment]
@MichaelRimler has an idea to replace the 6 hexes with a more complete visual representing the pharmaverse - he'll open this up to our community to volunteer ideas. so with this in mind i'll close this issue and we can replace with a new one to add whichever image is chosen.
