### ISSUE TITLE
[New package request] cardx

### ISSUE THREAD

**Issue by ddsjoberg** [pharmaverse/pharmaverse#305]
- [x] I have first considered whether there is already an existing pharmaverse package that could solve this need, or if I could combine forces with an existing effort to add my features to their existing package.

- [x] I confirm I have read https://pharmaverse.org/contribute/lead/ and my package follows the Inclusion Criteria for pharmaverse.

**Name and description of package**
Create extra Analysis Results Data (ARD) summary objects. The package supplements the simple ARD functions from the 'cards' package (already in the pharmaverse), exporting functions to put statistical results in the ARD format. These objects are used and re-used to construct summary tables, visualizations, and written reports. The cardx package supports 40+ regression model types, including the new developed mmrm package. Other methods include survival analysis, marginal means (or least-squares means), many methods for confidence interval derivation, and tests for treatment comparisons.

**Category of package**
TLGs

**Repository**
https://github.com/insightsengineering/cardx

**Package Maintainer**
@ddsjoberg 

**Who is involved in developing/maintaining this package?**
Roche, Novartis, Atorus
Roche is the copyright holder

**Considerations for pharmaverse inclusion**
Licensed under Apache License 2.0.
The package has 98% code coverage with checks on 4 versions of R on Ubuntu, Windows, and MacOS.
Each exported function includes associated examples on the website

**Overall fit in pharmaverse**
The cardx package is a companion to cards, which is already in the pharmaverse. Together, the packages cover the majority of methods needed for clinical trial result readouts. We plan to continue to add methods and accept contributions from others for new statistical methods.

**Comment by epijim** [comment]
Comment on `gtsummary` true here as well: https://github.com/pharmaverse/pharmaverse/issues/304#issuecomment-2269643179
