### ISSUE TITLE
Broken URLs

### ISSUE THREAD

**Issue by jimrothstein** [pharmaverse/pharmaverse#311]
On this page:   https://github.com/pharmaverse/pharmaverse/blob/main/content/contribute/ic/_index.en.md

3 broken URLS, but not certain what the correct urls should be.

> To help you find suitable open source packages to contribute your skills toward, check out **openpharma.pharmaverse.org.** 
> 
> **Here** you can see a range of open issues  ..... <snip> ..... 
> 
>  Over time, you might even make the **Leader Board!**
> 

3 broken URLS, but not certain what the correct urls should be.

1.  https://openpharma.pharmaverse.org   should be: 
 https://github.com/openpharma ?

Issues:

3. http://openpharma.pharmaverse.org/?nav=openissues    should be:  
https://github.com/openpharma/openpharma.github.io/issues  ?

Leaderboard

4. http://openpharma.pharmaverse.org/?nav=leaderboard  should be:  
https://github.com/openpharma/opensource_dashboard ?

**Comment by rossfarrugia** [comment]
@epijim @MathieuCayssol - what's the long term plans with the openpharma.pharmaverse.org page? will it be restored or should i remove the links and references from pharmaverse site?

thanks Jim for raising the issue!

**Comment by MathieuCayssol** [comment]
The AWS account has been shut down. The app is no longer available and I believe @epijim is planning to bring back a static content instead. 

I assume you can remove the link for the moment 👍
