### ISSUE TITLE
[New package request] {sdtm.oak}

### ISSUE THREAD

**Issue by rammprasad** [pharmaverse/pharmaverse#314]
- [x] I have first considered whether there is already an existing pharmaverse package that could solve this need, or if I could combine forces with an existing effort to add my features to their existing package.

- [x] I confirm I have read https://pharmaverse.org/contribute/lead/ and my package follows the Inclusion Criteria for pharmaverse.

**Name and description of package**
Name - {sdtm.oak}

https://cran.r-project.org/web/packages/sdtm.oak/index.html

Description - An EDC (Electronic Data Capture systems) and Data Standard agnostic solution that enables the pharmaceutical programming community to develop CDISC (Clinical Data Interchange Standards Consortium) SDTM (Study Data Tabulation Model) datasets in R. The reusable algorithms concept in ‘sdtm.oak’ provides a framework for modular programming and also can automate SDTM creation based on the standard SDTM spec.

**Category of package**
SDTM

**Repository**
https://github.com/pharmaverse/sdtm.oak

**Package Maintainer**
Rammprasad Ganapathy

**Who is involved in developing/maintaining this package?**
Rammprasad Ganapathy, Adam Forys, Edgar Manukyan, Rosemary Li, Preetesh Parikh, Lisa Houterloot, Yogesh Gupta, Omar Garcia, Ramiro Magno, Kamil Sijko, Shiyu Chen, Pattern Institute, F. Hoffmann-La Roche AG, Pfizer Inc, Transition Technologies Science.

**Considerations for pharmaverse inclusion**
Apache License (>= 2), 
automated test cases - 93.52% code coverage
Package Documentation - https://pharmaverse.github.io/sdtm.oak/index.html
Package documentation includes sample data, Vignette that explains step-by-step programming guide for programming SDTM domains, example - https://pharmaverse.github.io/sdtm.oak/articles/events_domain.html

**Overall fit in pharmaverse**
Why you believe this should belong in the pharmaverse? Please call out any novel or duplicative functionality relative to the existing pharmaverse packages.

The {sdtm.oak} package fills a critical gap in the Pharmaverse suite by enabling study programmers to create SDTM datasets in R, complementing the existing capabilities for ADaM and TLGs. This package is designed to be highly versatile, accommodating varying raw data structures from different EDC systems and external vendors. Moreover, {sdtm.oak} is data standards agnostic, meaning it supports both CDISC-defined data collection standards (CDASH) and various proprietary data collection standards defined by pharmaceutical companies. The reusable algorithms concept in {sdtm.oak} provides a framework for modular programming, making it a valuable addition to the Pharmaverse ecosystem. We plan to develop features in upcoming releases that can potentially automate SDTM creation based on standard SDTM specifications.

**Comment by ddsjoberg** [comment]
{sdtm.oak} fills an important gap and is a great match for the pharmaverse! 🕺🏼

**Comment by rossfarrugia** [comment]
@rammprasad FYI that this package will be added to the site over the next week as we're working on some other back-end infra fixes at the same time. Will let you know once added so that you can continue with the blog plans and raising awareness etc
