### ISSUE TITLE
[BUG] Link to DVOST group does not work on the Contribute subpage.

### ISSUE THREAD

**Issue by DamianRodziewicz** [pharmaverse/pharmaverse#322]
**Describe the bug**
Link to DVOST group does not work on the Contribute subpage.

**To Reproduce**
1. Go to https://pharmaverse.org/contribute/wg/
2. Click on [Data Visualisation and Open Source Technology (DVOST) working group](https://advance.phuse.global/pages/viewpage.action?pageId=327777)

**Expected behavior**
DVOST webpage - would this one be the correct one @mstackhouse? https://advance.hub.phuse.global/wiki/spaces/WEL/pages/26804419/Data+Visualisation+Open+Source+Technology 

**Screenshots**
Current result:
![Screenshot 2024-09-30 at 10 03 59](https://github.com/user-attachments/assets/3828e98a-df42-4ecb-b786-c59a24d79b3f)

**Comment by mstackhouse** [comment]
Already merged but @DamianRodziewicz  yes right link.

**Comment by DamianRodziewicz** [comment]
Thank you! I got a confirmation from @sankhadeepdutta on Slack that it was confirmed with you prior to merging :+1:
