### ISSUE TITLE
roxytractor - R package knowledge extractor

### ISSUE THREAD

**Issue by galachad** [pharmaverse/pharmaverse#335]
- [x] I have first considered whether there is already an existing pharmaverse package that could solve this need, or if I could combine forces with an existing effort to add my features to their existing package.

- [x] I confirm I have read https://pharmaverse.org/contribute/lead/ and my package follows the Inclusion Criteria for pharmaverse.

**Name and description of package**
roxytractor - A tool designed to extract key information from roxygen2 documentation within R packages, simplifying the process of converting documentation into structured data efficiently. roxytractor extracts documentation using the roxygen2 roclet and package metadata, outputting it in a simple tabular format.

**Category of package**
Utility

**Repository**
The package is not yet open source.

**Package Maintainer**
Currently, only me - Adam Forys

**Who is involved in developing/maintaining this package?**
Roche

**Considerations for pharmaverse inclusion**
The package could be made open source under the Apache 2 license. It is still in the early stages, and its structure will require modifications to accommodate all use cases.

**Overall fit in pharmaverse**
We are using it to create a corpus for open source and inner source packages. While the package can extract knowledge from any R package and is general in nature, we are mainly following pharmaverse's template rules.

**Comment by rossfarrugia** [comment]
@galachad https://github.com/pharmaverse/roxytractor is now available and I made you admin. I'll add something to the website to note that this is a work in progress (hopefully to bring more awareness/contributors to your effort) and then once the package has a more formal release and meets the inclusion criteria (https://pharmaverse.org/contribute/lead/) then you could make a new issue here to request it to be officially added to the pharmaverse list of recommended packages.
