### ISSUE TITLE
Some badge stats not being added for packages

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#342]
@sankhadeepdutta the website looks good now with all the recent clean-ups, but 2 of the packages under `data/packages` (i.e. part of the pharmaverse list) don't have the full stats added (cran/contributors/stars) as below:

![image](https://github.com/user-attachments/assets/e123cd0b-9397-4c97-85c9-ddca69862d59)

![image](https://github.com/user-attachments/assets/fea020ff-859c-4eb7-8a55-600d96ea293d)

Can you double check please? and feel free to make a commit for this straight to `develop` as you have write access here now and then you can make a PR to `main` and i'll review.

**Comment by rossfarrugia** [comment]
> Hi @rossfarrugia, as I can check in the `add_badges.R` script, the badge information is fetched from https://openpharma.github.io/generate_badges/output/data.parquet, which does not contain all the package stats. Also, the `diffdf` package info does not exist in the data file.

@sankhadeepdutta looks like the openpharma pipeline fails currently: https://github.com/openpharma/generate_badges/actions/runs/11885214560 - FYI @epijim 
What about setting up similar code to what James has done in https://github.com/openpharma/generate_badges/blob/main/R/create_badge_data.R but directly in our `add_badges.R` script and only for the pharmaverse packages under `data/packages`? Then we break the dependency on this external pipeline.

**Comment by sankhadeepdutta** [comment]
> > Hi @rossfarrugia, as I can check in the `add_badges.R` script, the badge information is fetched from https://openpharma.github.io/generate_badges/output/data.parquet, which does not contain all the package stats. Also, the `diffdf` package info does not exist in the data file.
> 
> @sankhadeepdutta looks like the openpharma pipeline fails currently: https://github.com/openpharma/generate_badges/actions/runs/11885214560 - FYI @epijim What about setting up similar code to what James has done in https://github.com/openpharma/generate_badges/blob/main/R/create_badge_data.R but directly in our `add_badges.R` script and only for the pharmaverse packages under `data/packages`? Then we break the dependency on this external pipeline.

@rossfarrugia Yes, I think this will be a good approach. I'll try this.

**Comment by sankhadeepdutta** [comment]
hi @rossfarrugia, could you pls update the scope of the GitHub token?
<img width="491" alt="Screenshot 2024-11-20 at 4 28 22 PM" src="https://github.com/user-attachments/assets/9cd38d96-cc5d-47e8-8353-73c5492c8b6f">
