### ISSUE TITLE
Blog and comments feature

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#36]
As discussed @epijim one for later once our website gets more established:
add a blog section on site - with ability for people to comment on. could use to share things like known challenges with R and links to important open issues like the one for haven

**Comment by epijim** [comment]
I've added discussion.pharmaverse.org

**Comment by rossfarrugia** [comment]
@epijim i like it! - let us know when incorporated into the site as well. not essential for the Jan review but as we have it now might as well if not huge effort

**Comment by rossfarrugia** [comment]
@mstackhouse @MichaelRimler @skalappu any thoughts on this one?? re-visiting it now i tend to think we have this covered via Slack and LinkedIn group for now. it just seems like another place we'd need to monitor and maintain. i propose to close this issue and not incorporate into the site. do you agree?

**Comment by skalappu** [comment]
@rossfarrugia  -  I agree that in too many places, information gets scratched, and sometimes it becomes duplicated.  More monitoring and moderating come with their challenge.

**Comment by rossfarrugia** [comment]
Agree - will close this and please anyone comment if disagree and we could re-look over time.

**Comment by mstackhouse** [comment]
Late here but I concur - with a blog it's another place to monitor, maintain, and moderate.
