### ISSUE TITLE
Contact form needs to post to slack

### ISSUE THREAD

**Issue by epijim** [pharmaverse/pharmaverse#47]
![image](https://user-images.githubusercontent.com/2760096/146397945-52c88e6c-3a1d-4cd9-8b0b-b31ede3c4e3b.png)

**Comment by rossfarrugia** [comment]
@epijim seems to work fine so happy if you want to close this issue

**Comment by epijim** [comment]
![image](https://user-images.githubusercontent.com/2760096/151167284-2e0cc76b-2f34-4c14-846a-087ef8865024.png)
