### ISSUE TITLE
Add badges so repos can link back to the pharmaverse.

### ISSUE THREAD

**Issue by epijim** [pharmaverse/pharmaverse#48]
Can tweak this - e.g. add logo, change text. But general idea is they can add this - e.g. `Tplyr`, `rtables`, `admiral` - once they are 'part' of the pharmaverse, we autogenerate and host badges on a fixed URL bath they can then add to their repos.

![image](https://user-images.githubusercontent.com/2760096/146579216-f85fd231-b171-4fc6-ac39-98bf76aca6ed.png)

**Comment by rossfarrugia** [comment]
pasting request from slack: can you add a bullet to explain this under "Package co-lead" section of https://pharmaverse.org/contribute/? i think that's where it would sit best and explain the benefits of this briefly - hopefully in time it's seen as like a mark of honour

**Comment by epijim** [comment]
added e section - sorry, forgot you said package co-lead when implementing this

**Comment by rossfarrugia** [comment]
@epijim no worries - feel free to play around with wher you think best, as long as it's easy to follow that things like this and the contracts are most relevant to developers/package leads that want to make a new pharmaverse collaboration.

i see now there's some new incomplete pages: https://pharmaverse.org/contribute/help/, https://pharmaverse.org/contribute/lead/, https://pharmaverse.org/contribute/governance/, https://pharmaverse.org/contribute/council/. i guess your plan is to split out what i drafted at https://pharmaverse.org/contribute/ across these? let me know when done and i can take a look. good if we can do that before people start their review in Jan. (Note it's my last half-day working today but i can take a look at anything first thing when back as needed, but i trust your calls anyway).
