### ISSUE TITLE
Placeholder for other languages page

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#51]
Briefly discussed with Michael an idea to add to the site later a reference page for anything open source useful for pharma beyond R language only, e.g. links to cdisc core, katja's site, open source python packages etc.

Just leaving this as a placeholder for now and can come back to later after the meeting with Sam & Katja from cdisc cosa.

**Comment by rossfarrugia** [comment]
I want to add to our pharmaverse site a page called something like "Beyond R" where we link to other useful clinical reporting open source resources that focus on any other language besides R. Here's a list of the key links I would include for now:

- CDISC COSA (https://cosa.cdisc.org/) - with a call-out to CORE
- Katja Glass' site (https://www.glacon.eu/portal/overviewVisual.html) 
- PHUSE WGs (https://advance.phuse.global/pages/viewpage.action?pageId=327777)
- R Consortium WGs & R Validation Hub - with a note to say obviously not "beyond R" but still hugely important efforts that anyone using pharmaverse should be aware of

**Comment by epijim** [comment]
@rossfarrugia - maybe a different name? As we have things in the pharmaverse that aren't strictly speaking R already. e.g. thevalidatoR is a github-action (for R packages 😆 ). Maybe like 'Beyond tools' or 'Beyond code'?

Tracking health / activity on open source codebases for Pharma: openpharma.github.io (also the data source for pharmaverse)

Maybe we could go as far as seperating out working groups? e.g. Tad - I guess you have lots of content there to share a landscape on all the working groups.

**Comment by lewandt** [comment]
There are also other materials, links and so on. Maybe collection of them would be a useful. There is also TransCelerate solutions: https://www.transceleratebiopharmainc.com/our-solutions/

**Comment by rossfarrugia** [comment]
Adding discussion from email around should we include python packages like https://github.com/GSK-Biostatistics/neointerface

My view: interesting question, probably a bit of a grey area for us and so I'll give my general thinking without having looked too much into the specifics of that package. James pointed out that we do already include some things beyond R in the pharmaverse, e.g. there's a github action that helps validating R packages, but then it still has a link to R and helping people move to this. If we also add a list of python, julia, etc codes then we'd need to curate these and organise them as well as our R list. In a way I think that's what the pharmaverse should grow to over time, but using R as the first pathway into getting the industry collaborating around open source. I think we discussed this in the very early days of drafting our charter. So short answer from me: yes relevant for our vision, but no I wouldn't include on the site just yet.
