### ISSUE TITLE
People section lost J&J contacts

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#63]
@epijim Tad spotted that J&J folks like Sumesh and Sairam had been lost from the contacts section. is it because you need their github handles? let me know what you need and happy to try and push for this info.

**Comment by rossfarrugia** [comment]
Requested Sairam's github handle by mail and we have Sumesh now once he accepts invite - sent reminder

**Comment by epijim** [comment]
Yeah, it's due to above (didn't have gh).

**Comment by epijim** [comment]
see commit f16b43d - 50% done, but need Sairam's github handle.

**Comment by rossfarrugia** [comment]
@epijim Sairam replied - his handle is gorthis. i'll send an invite for him to join the org.
