### ISSUE TITLE
Add a people page

### ISSUE THREAD

**Issue by epijim** [pharmaverse/pharmaverse#7]
List all the people involved

**Comment by epijim** [comment]
Added a crude placeholder.

![image](https://user-images.githubusercontent.com/2760096/129791410-a563eb89-7a68-4039-928d-45509c5df5dc.png)

Content is hopefully quite simply managed by the following yaml (in `data/contributors.yaml`).

![image](https://user-images.githubusercontent.com/2760096/129791708-60cc7948-6990-4ee5-80b6-1be41c218554.png)

**Comment by epijim** [comment]
@rossfarrugia - can you take a look (scroll to bottom of https://pharmaverse.org/)

**Comment by rossfarrugia** [comment]
awesome, thanks @epijim! once we have the WGs etc worked out we can start to update, but I like the look.

**Comment by rossfarrugia** [comment]
@epijim - i can edit the yaml file but wondering where the set-up of how this renders on the front page is stored? e.g. formatting of the section headers and ability to add images etc.

instead of Executive section i want to replace with:

###Council
<Atorus logo> Mike Stackhouse
<GSK logo> Michael Rimler
<Janssen logo> Sumesh Kalappurakal
<Roche logo> Ross Farrugia

we can also delete the end2end WG, the other 3 are fine as they are for now. hopefully can add some more names from the other companies over time.

**Comment by rossfarrugia** [comment]
can we make the email addresses i added as hyperlinks too?

**Comment by rossfarrugia** [comment]
refer to https://github.com/pharmaverse/meetings/issues/15 for content

**Comment by epijim** [comment]
## logos

Logos are possible, but means doing the data format a little more sophisticated (so we don't have to hardcode). e.g. I just use simple lists at the moment (see below). 

I think the proper way to do it would be to have people profiles, and then one parameter in the profile is a list of working groups. I think we should do that, but it's probably 1-2 hours work as we'd need to rewrite the template and I don't know how hugo data templates work off by heart so would need to google/experiment. I'd maybe say to keep text names, but I'll make anissue to do it properly (maybe this weekend I think I can have a go).

![image](https://user-images.githubusercontent.com/2760096/146029142-b9e82fa0-7b36-494d-9050-7c9372029ee4.png)

## groups

Added the groups - I kept website separate though as that is one we can keep asynchronous (as it's a codebase, so the discussions would be in issues), so instead I just pointed to the project board, and then the list of people is based on who did contribute (as it's pulled from git history).

**Comment by epijim** [comment]
implemented in https://github.com/pharmaverse/pharmaverse/commit/af973141299a2cba4b1ceb1f3c8ad6b2b79b84b9

**Comment by rossfarrugia** [comment]
all good for me James! logos are a nice to have. i like the profile idea for later - plus we probably could add a description of scope of each WG too, but i wouldn't worry for this first review version.

**Comment by epijim** [comment]
initial feature done, closing and moving stage 2 to #44
