### ISSUE TITLE
Check links to package repos and sites all work

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#79]
e.g. Oak is closed source at moment so links go to Roche-specific pages - need to remove and check any others

**Comment by statasaurus** [comment]
I was just clicking around and there are github links for teal, nest, etc. But, those don't work for people not part of the repos. So should they be taken down until they have been make open source?

**Comment by rossfarrugia** [comment]
yep agree - this one's on my to-do list to update

**Comment by rossfarrugia** [comment]
FYI @statasaurus James chose to leave in the links for NEST as although closed the companies/individuals involved do have access and there's an explanation given, but i'll get Oak links removed as they point to Roche areas anyway that wouldn't be the right links even when we open source

**Comment by statasaurus** [comment]
Would it be possible to change the hex and name on the nest organisation? At the moment no where on that page says nest which is a touch confusing for users

**Comment by rossfarrugia** [comment]
@epijim @lewandt please see Christina request above.

**Comment by rossfarrugia** [comment]
NEST now open source and explanation text on https://pharmaverse.org/e2eclinical/tlg/
