### ISSUE TITLE
How to contribute page

### ISSUE THREAD

**Issue by epijim** [pharmaverse/pharmaverse#8]
I’m thinking worth to have a dedicated page to something like “How to contribute?” and then this page could include: (note: maybe this comes under your Tools and Guidance placeholder? But it should be made easy to find)
Recommendations on how could contribute to existing packages/codebases
Step-by-Step guide for how to initiate a new package collaboration under pharmaverse - which would include how to reach out to us, and then all our recommendations around contracts/licensing/etc, contribution guidelines/prog style guide

**Comment by rossfarrugia** [comment]
Work in progress: https://pharmaverse.org/contribute/ - gaps need to be filled from the actions people are working through currently.
