### ISSUE TITLE
admiral team requested to add any ADaM e2e pieces to pharmaverse site

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#80]
Will add more details when I know but includes:
- adding new metatools package
- e2e vignette of how to use metacore-metatools-admiral-xportr together to create ADaM

Rationale: as the need is to use more than one pharmaverse package it makes sense not to bury this only in admiral site. Admiral site would instead link to pharmaverse page here.

**Comment by rossfarrugia** [comment]
@statasaurus see the instructions here on how to update the site: https://github.com/pharmaverse/pharmaverse/blob/main/README.md. Try out adding the new vignette content and we could discuss where it would look best on the site. I was originally just thinking to add it to https://pharmaverse.org/e2eclinical/adam/.

FYI @epijim - can you add Christina to the AWS access for her to be able to do UAT step?

**Comment by rossfarrugia** [comment]
you could also metatools under https://pharmaverse.org/e2eclinical/metadata/.  

@epijim how do we add this to the shield option for https://pharmaverse.org/contribute/badges/ too? so that Christina can add this to the metatools readme.

**Comment by epijim** [comment]
> FYI @epijim - can you add Christina to the AWS access for her to be able to do UAT step?

not sure what you mean here. AWS is accessed via gh-actions, so Christina doesn't need access to anything.

**Comment by epijim** [comment]
All the metadata logic is over in github.com/openpharma/openpharma.github.io (that repo is basically one big crawler). So it needs to be added here: https://github.com/openpharma/openpharma.github.io/blob/master/openpharma_included.yaml

what's the github repo for it?

**Comment by epijim** [comment]
For the vignette itself - do we want full building vignettes on fake data here on the site? Or could we say through them in another repo and just link out? 

Thinking from the build perspective - as this whole site is re-built fairly frequently, and it also opens us up to the build process failing more (e.g. R package issues that effect the vignettes, but not the 'normal' website.

**Comment by rossfarrugia** [comment]
@epijim cool about AWS - it was just you mentioned before "_I guess we can handle the AWS account a level below that? eg just people working on the website backend rather than the council._". I misunderstood.

Repo: https://github.com/pharmaverse/metatools 

I'm open with the vignettes to whatever you suggest. I'm not sure yet if the e2e vignette will use fake data - I'd defer to @statasaurus. It will need to explain how the packages work together with example code, but I don't think it'll need to be as heavy as the admiral vignettes like https://pharmaverse.github.io/admiral/articles/adsl.html

**Comment by epijim** [comment]
Ahh, for the AWS thing. Yeah - to push to the UAT (e.g. publish from the develop branch to the S3 hosted UAT site) no access is needed for a user, as it's via gh-actions.

The actual AWS account I still haven't moved off my cc 😆  - maybe we cross that bridge if we run into anything where the AWS access is needed? I have a deadline to move it off mine of June, as that's when our open source metadata intern should start - and he'll need access to AWS as it's where openpharma writes all the data it scrapes (which is then pulled into pharmaverse).

**Comment by epijim** [comment]
We have a new non-profit between JJ, Novartis, Roche and Beigene that might be able to 'host' it (I haven't asked, but I'm curious if IT would allow us to let someone from another pharma to have access to a Roche AWS account).

**Comment by epijim** [comment]
> I'm open with the vignettes to whatever you suggest. I'm not sure yet if the e2e vignette will use fake data - I'd defer to @statasaurus. It will need to explain how the packages work together with example code, but I don't think it'll need to be as heavy as the admiral vignettes like https://pharmaverse.github.io/admiral/articles/adsl.html

Cool - if it's like a narrative (a bit like what we have on the TLG page right now), then for sure no issues on the site. Maybe let's circle back if the idea is to add real R code against fake data to figure out if it gets rebuilt each time the site builds, or we move it outside that process.

**Comment by statasaurus** [comment]
The idea would be it would be R code against fake data. The data is currently in other packages so we can just load it from there, but in might take about 10-15 seconds to run end to end

**Comment by rossfarrugia** [comment]
@statasaurus i think this is the main home of the e2e ADSL vignette you're working on (or it should be from now at least!). the main other discussions were at https://github.com/pharmaverse/admiral/issues/796, like i commented there: _when you're ready make a PR for this at https://github.com/pharmaverse/end_to_end_examples so easier for us to go through and add review comments to the code. I have some general comments like some typos in the comments and i would like to suggest some Intro text at the top to discuss what each of the packages is covering here, so people are clear on the impact of say if they chose not to use 1 of the 4 pharmaverse packages. Happy to look in more depth though._

**Comment by rossfarrugia** [comment]
Closing now as we have separate repo for e2e examples (https://github.com/pharmaverse/end_to_end_examples) and the site has been linked in pharmaverse page now.
