### ISSUE TITLE
pharmaverse WG reps - include Christina

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#81]
@MichaelRimler i would suggest to replace you in what we are calling the "Technology and templates WG" with Christina (@statasaurus) if you agree? She has great ideas for future pieces to add to the site, and is already going to be involved with adding the e2e ADaM vignette. Or fine if you prefer we add Christina and keep you as well from GSK under that WG?

**Comment by MichaelRimler** [comment]
No problem.
