### ISSUE TITLE
Minor changes to nomenclature - GitHub and pharmaverse

### ISSUE THREAD

**Issue by MichaelRimler** [pharmaverse/pharmaverse#84]
There are instances of 'pharmaverse' not in all lower case - suggest we are consistent due to case sensitivity

There are instances of 'GitHub' as 'Github' or 'github'. When 'G', suggest 'H' since this is the preference of GitHub itself (As far as I can tell).

**Comment by rossfarrugia** [comment]
think i got them all now once the above commits are merged, but shout in future if you spot any more missed
