### ISSUE TITLE
Suggest a click on outside resources opens in new tab/window

### ISSUE THREAD

**Issue by MichaelRimler** [pharmaverse/pharmaverse#85]
Whenever possible, clicking on a link that is external to pharmaverse.org should open in a new window/tab (e.g., the GitHub repo). This keeps the user within the site instead of navigating them away.

**Comment by rossfarrugia** [comment]
good idea! @epijim know how to do this? i found this link about it https://stackoverflow.com/questions/41915571/open-link-in-new-tab-with-github-markdown-using-target-blank

**Comment by MichaelRimler** [comment]
target=“_blank” or whatever the correct syntax is is HTML 4 code. I’ve been successful in some places of blogdown, but not all. The basic flat Rmd worked fine. But I think there were issues with links in the header. I’m curious if this is feasible with the site build code. Probably in some places, but maybe not all. 

Incidentally, replace the keyword _blank with any string and you are naming the tab. So you can always send the link to the same (named) tab.

**Comment by rossfarrugia** [comment]
i don't see this being prioritised currently - could re-open later if sufficient interest, but i'm trying to clean up stale issues in this repo.
