### ISSUE TITLE
Add links to R Validation Hub or TransCelerate MoA

### ISSUE THREAD

**Issue by MichaelRimler** [pharmaverse/pharmaverse#86]
In the section "Is this validated/GxP/regulatory assured", perhaps add resources on this topic such as the R Validation Hub or the TransCelerate MoA project (https://www.transceleratebiopharmainc.com/initiatives/modernization-statistical-analytics/).
![image](https://user-images.githubusercontent.com/47422662/151084682-3a900899-547e-4788-9181-8063ecc4489d.png)

**Comment by rossfarrugia** [comment]
Will do - also linking this to 2 other relevant issues #67 & #51
