### ISSUE TITLE
'Health' is a misleading badge 

### ISSUE THREAD

**Issue by epijim** [pharmaverse/pharmaverse#92]
**Describe your idea**
'Health' is a misleading badge as it's only 'open source health', and there is no indication of how it's defined.

**Additional context**
We also print the 'riskmetric' badges generated by openpharma.

**Comment by epijim** [comment]
Solution - rename to 'OS Health', and make the clickout go to a badge that defines the score.

@epijim to decouple and make docs page for the OS health. 

Note - longer term plan to move to something like Percival from GrimoreLabs for better OS health metadata.

**Comment by epijim** [comment]
![image](https://user-images.githubusercontent.com/2760096/154218011-dda8d81f-6a66-4b86-b182-fb55b683617b.png)
 badges fixed - the badge redirection should be fixed next PR

**Comment by rossfarrugia** [comment]
@epijim since we moved admiral's repo the score is showing as 0 but on the site when you click through it explains 86. maybe its not been updated to look at the new pharmaverse org repo?

**Comment by epijim** [comment]
I think I fixed it in an update today to Openpharma. Will close as initial issue is done, and make two new bug tickets (for admiral and timber)
