### ISSUE TITLE
e2e clinical reporting vignette 

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaverse#93]
**Describe your idea**
Following James's thread in the Slack... reminder to look into an e2e vignette that ties together all the packages later such as SDTM->ADaM->TLG->eSub via various pharmaverse packages. This will tie in with our efforts for the PHUSE US Connect workshop

**Comment by statasaurus** [comment]
So the first one of these SDTm -> ADaM is functionally done and [here](https://github.com/pharmaverse/end_to_end_examples/blob/main/adsl.html). There are a few updates I am going to make and I am going to add some more explanation around it. But, it is done enough to work out how we want to add it to the website. @epijim do you have a way you want to add these to the website?

**Comment by statasaurus** [comment]
Given we have spoken about this I am going to close this issue
