### ISSUE TITLE
Change "e2e" wording to "End to End"

### ISSUE THREAD

**Issue by statasaurus** [pharmaverse/pharmaverse#94]
**Describe the bug**
While e2e is a fairly common acronym, it is still be to avoid for accessibility.

**Comment by rossfarrugia** [comment]
fair point - i'll update for this

**Comment by statasaurus** [comment]
Additionally TLGs isn't standard. At GSK we call them TFLs so it might also be worth changing this for the same reason

**Comment by rossfarrugia** [comment]
thanks - TLG is all over the place so i added the easy fix here by explaining on the TLG page:

TLGs (tables, listings, and graphs - also known as TLFs/TFLs with F for figures)
